# Import e tratamento dos dados

## Import de dados

In [1]:
import pandas as pd
import chardet

In [2]:
with open("02_dados_pre_tratados/dados_camara_2019.csv", "rb") as f:
    result = chardet.detect(f.read())

df_camara_2019 = pd.read_csv("02_dados_pre_tratados/dados_camara_2019.csv", sep=";", encoding=result['encoding'])
df_camara_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,8,1,28/02/2019,Câmara Municipal de Cajazeiras,08.841.553/0001-89,"520.371,52","520.371,52","520.371,52",0
1,11,2,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,487,487,487,0
2,12,3,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"10.550,00","10.550,00","10.550,00",0
3,13,4,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"16.379,94","16.379,94","16.379,94",0
4,17,5,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"12.250,00","12.250,00","12.250,00",0
...,...,...,...,...,...,...,...,...,...
61,18,72,31/12/2019,Marcos Helder,646.603.624-34,"1.600,00","1.600,00","1.600,00",0
62,19,73,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"49.409,81","49.409,81","49.409,81",0
63,20,74,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"2.800,00","2.800,00","2.800,00",0
64,28,76,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"30.257,04","30.257,04","30.257,04",0
65,26,77,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,"134.239,06","134.239,06","134.239,06",0

In [3]:
df_instituto_previdencia_2019 = pd.read_csv("02_dados_pre_tratados/dados_instituto_previdencia_2019.csv", sep=";", encoding=result['encoding'])
df_instituto_previdencia_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,146,1,03/01/2019,CAIXA ECONOMICA FEDERAL,00.360.305/0040-10,"836,04","836,04","836,04",0
1,146,2,03/01/2019,BANCO DO BRASIL SA,00.000.000/1641-19,"4,6","4,6","4,6",0
2,146,4,10/01/2019,ENERGISA - SAELPA,09.095.183/0001-40,"309,49","309,49","309,49",0
3,146,5,10/01/2019,CAGEPA,09.123.654/0001-87,"68,24","68,24","68,24",0
4,150,6,10/01/2019,TELEMAR NORTE LESTE S.A.(OI FIXO),33.000.118/0001-79,"164,47","164,47","164,47",0
...,...,...,...,...,...,...,...,...,...
386,146,392,31/12/2019,INFOPRINTER COMERCIO & SERVIÇOS,14.745.112/0001-86,525,525,0,525
387,146,393,31/12/2019,FRANCISCO LUCIANO DE OLIVEIRA,09.238.207/0001-73,"419,95","419,95",0,"419,95"
388,146,394,31/12/2019,TELEMAR NORTE LESTE S.A.(OI FIXO),33.000.118/0001-79,"165,09","165,09",0,"165,09"
389,138,395,31/12/2019,INSS,29.979.036/0169-00,"4.293,03","4.293,03",0,"4.293,03"
390,138,396,31/12/2019,INSS,29.979.036/0169-00,"4.704,30","4.704,30",0,"4.704,30"

In [4]:
df_prefeitura_2019 = pd.read_csv("02_dados_pre_tratados/dados_prefeitura_2019.csv", sep=";", encoding=result['encoding'])
df_prefeitura_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,954,18,02/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,"30.000,00","27.358,10","27.358,10","2.641,90"
1,1042,27,02/01/2019,ELIANE DO NASCIMENTO CAMPOS,13.094.898/0001-56,"2.032,00","2.032,00","2.032,00",0
2,922,65,07/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,"75,82","75,82","75,82",0
3,922,68,07/01/2019,MAXICASA COMERCIO CONSTRUCOES E SERVICOS LTDA....,03.278.968/0001-72,0,0,0,0
4,935,94,21/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,"153,66","153,66","153,66",0
...,...,...,...,...,...,...,...,...,...
7049,724,7181,31/12/2019,"FERREIRA E BRITO LOCAÇÕES DE AUTOMÓVEIS, MÁQUI...",17.340.620/0001-72,"2.900,00",0,0,"2.900,00"
7050,728,7192,31/12/2019,JOSE EPITACIO DA SILVA NETO,086.381.214-74,"1.497,00","1.497,00",0,"1.497,00"
7051,681,7206,31/12/2019,PEDRO MANGUEIRA DE AQUINO,24.099.731/0001-02,"9.254,52","9.254,52",0,"9.254,52"
7052,681,7208,31/12/2019,PEDRO MANGUEIRA DE AQUINO,24.099.731/0001-02,"4.531,32","4.531,32",0,"4.531,32"
7053,719,7214,31/12/2019,J. V. COMERCIO DE DERIVADOS DE PETROLEO LTDA,30.733.130/0001-02,"9.183,00",0,0,"9.183,00"

In [5]:
df_sctrans_2019 = pd.read_csv("02_dados_pre_tratados/dados_sctrans_2019.csv", sep=";", encoding=result['encoding'])
df_sctrans_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,79,1,03/01/2019,FIUZA CORDEIRO CONSULTORIA AUDITORIA E ASSESSO...,11.516.881/0001-14,"1.500,00","1.500,00","1.500,00",0
1,74,2,04/01/2019,JOSE INALDO DE LIRA - ME MADEREIRA PIRANHENSE ...,10.752.764/0001-97,980,980,980,0
2,79,3,07/01/2019,MOISES RODRIGUES DA SILVA,12.761.023/0001-06,500,500,500,0
3,74,4,09/01/2019,ELETRO PECAS SA LTDA,40.982.464/0001-65,110,110,110,0
4,83,5,09/01/2019,OI FIXO - TELEMAR NORTE LESTE S/A,33.000.118/0012-21,"162,18","162,18","162,18",0
...,...,...,...,...,...,...,...,...,...
793,71,808,30/12/2019,IPAM - INSTITUTO DE PREVIDENCIA E ASSISTENCIA ...,12.724.464/0001-20,"4.359,36","4.359,36","4.359,36",0
794,71,809,30/12/2019,IPAM - INSTITUTO DE PREVIDENCIA E ASSISTENCIA ...,12.724.464/0001-20,"8.026,92","8.026,92","8.026,92",0
795,71,810,30/12/2019,IPAM - INSTITUTO DE PREVIDENCIA E ASSISTENCIA ...,12.724.464/0001-20,"4.315,05","4.315,05",0,"4.315,05"
796,66,811,30/12/2019,INSS - INSTITUTO NACIONAL DO SEGURO SOCIAL,29.979.036/0169-00,"2.412,89","2.412,89",0,"2.412,89"
797,74,812,30/12/2019,J. V. COMERCIO DE DERIVADOS DE PETROLEO LTDA,30.733.130/0001-02,"4.143,86","4.143,86",0,"4.143,86"

## Tratamento dos DataFrames

In [6]:
# Definindo tipos das colunas antes de ler o dataset
columns_types = {'Empenhado(R$)':float,
                'Liquidado(R$)':float,
                'Pago(R$)':float,
                'Saldo(R$)':float}

In [7]:
'''
Função para tratamento dos valores monetários

'''

def tratar_valores(valor):
    
    '''
        Primeiramente, procura-se a localização do ponto, que separava os milhares, e a vírgula que definia os centavos de reais.
    '''
    posicao_virgula = valor.find(',')
    posicao_ponto = valor.find('.') 
    
    '''
        Após o armazenamento das posições de cada separador, armazenava o valor em uma nova string, sem os pontos e vírgulas, 
        e encontrava a nova posição do separador, agora um ponto.
    '''
    string = ''.join(filter(str.isalnum, valor))
    nova_posicao_ponto = posicao_virgula - (len(valor) - len(string))

    '''
        Por fim, após verificar qual condição a nova string se encaixava, retornava-se a nova string com o devido tratamento.
    '''
    if len(string) == len(valor):
        return valor
    
    elif posicao_ponto != -1:        
        string = string[0:nova_posicao_ponto+1] + '.' + string[nova_posicao_ponto+1:]
        return string
    
    else:
        string = string[0:posicao_virgula] + '.' + string[posicao_virgula:]
        return string

### Tratando dados

In [8]:
df_camara_2019['Empenhado(R$)'] = df_camara_2019['Empenhado(R$)'].apply(tratar_valores)
df_camara_2019['Pago(R$)'] = df_camara_2019['Pago(R$)'].apply(tratar_valores)
df_camara_2019['Liquidado(R$)'] = df_camara_2019['Liquidado(R$)'].apply(tratar_valores)
df_camara_2019['Saldo(R$)'] = df_camara_2019['Saldo(R$)'].astype('object')

df_camara_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,8,1,28/02/2019,Câmara Municipal de Cajazeiras,08.841.553/0001-89,520371.52,520371.52,520371.52,0
1,11,2,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,487,487,487,0
2,12,3,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,10550.00,10550.00,10550.00,0
3,13,4,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,16379.94,16379.94,16379.94,0
4,17,5,28/02/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,12250.00,12250.00,12250.00,0
...,...,...,...,...,...,...,...,...,...
61,18,72,31/12/2019,Marcos Helder,646.603.624-34,1600.00,1600.00,1600.00,0
62,19,73,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,49409.81,49409.81,49409.81,0
63,20,74,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,2800.00,2800.00,2800.00,0
64,28,76,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,30257.04,30257.04,30257.04,0
65,26,77,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,134239.06,134239.06,134239.06,0

In [9]:
df_instituto_previdencia_2019['Empenhado(R$)'] = df_instituto_previdencia_2019['Empenhado(R$)'].apply(tratar_valores)
df_instituto_previdencia_2019['Pago(R$)'] = df_instituto_previdencia_2019['Pago(R$)'].apply(tratar_valores)
df_instituto_previdencia_2019['Liquidado(R$)'] = df_instituto_previdencia_2019['Liquidado(R$)'].apply(tratar_valores)
df_instituto_previdencia_2019['Saldo(R$)'] = df_instituto_previdencia_2019['Saldo(R$)'].apply(tratar_valores)

df_instituto_previdencia_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,146,1,03/01/2019,CAIXA ECONOMICA FEDERAL,00.360.305/0040-10,836.04,836.04,836.04,0
1,146,2,03/01/2019,BANCO DO BRASIL SA,00.000.000/1641-19,4.6,4.6,4.6,0
2,146,4,10/01/2019,ENERGISA - SAELPA,09.095.183/0001-40,309.49,309.49,309.49,0
3,146,5,10/01/2019,CAGEPA,09.123.654/0001-87,68.24,68.24,68.24,0
4,150,6,10/01/2019,TELEMAR NORTE LESTE S.A.(OI FIXO),33.000.118/0001-79,164.47,164.47,164.47,0
...,...,...,...,...,...,...,...,...,...
386,146,392,31/12/2019,INFOPRINTER COMERCIO & SERVIÇOS,14.745.112/0001-86,525,525,0,525
387,146,393,31/12/2019,FRANCISCO LUCIANO DE OLIVEIRA,09.238.207/0001-73,419.95,419.95,0,419.95
388,146,394,31/12/2019,TELEMAR NORTE LESTE S.A.(OI FIXO),33.000.118/0001-79,165.09,165.09,0,165.09
389,138,395,31/12/2019,INSS,29.979.036/0169-00,4293.03,4293.03,0,4293.03
390,138,396,31/12/2019,INSS,29.979.036/0169-00,4704.30,4704.30,0,4704.30

In [10]:
df_prefeitura_2019['Empenhado(R$)'] = df_prefeitura_2019['Empenhado(R$)'].apply(tratar_valores)
df_prefeitura_2019['Pago(R$)'] = df_prefeitura_2019['Pago(R$)'].apply(tratar_valores)
df_prefeitura_2019['Liquidado(R$)'] = df_prefeitura_2019['Liquidado(R$)'].apply(tratar_valores)
df_prefeitura_2019['Saldo(R$)'] = df_prefeitura_2019['Saldo(R$)'].apply(tratar_valores)

df_prefeitura_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,954,18,02/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,30000.00,27358.10,27358.10,2641.90
1,1042,27,02/01/2019,ELIANE DO NASCIMENTO CAMPOS,13.094.898/0001-56,2032.00,2032.00,2032.00,0
2,922,65,07/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,75.82,75.82,75.82,0
3,922,68,07/01/2019,MAXICASA COMERCIO CONSTRUCOES E SERVICOS LTDA....,03.278.968/0001-72,0,0,0,0
4,935,94,21/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,153.66,153.66,153.66,0
...,...,...,...,...,...,...,...,...,...
7049,724,7181,31/12/2019,"FERREIRA E BRITO LOCAÇÕES DE AUTOMÓVEIS, MÁQUI...",17.340.620/0001-72,2900.00,0,0,2900.00
7050,728,7192,31/12/2019,JOSE EPITACIO DA SILVA NETO,086.381.214-74,1497.00,1497.00,0,1497.00
7051,681,7206,31/12/2019,PEDRO MANGUEIRA DE AQUINO,24.099.731/0001-02,9254.52,9254.52,0,9254.52
7052,681,7208,31/12/2019,PEDRO MANGUEIRA DE AQUINO,24.099.731/0001-02,4531.32,4531.32,0,4531.32
7053,719,7214,31/12/2019,J. V. COMERCIO DE DERIVADOS DE PETROLEO LTDA,30.733.130/0001-02,9183.00,0,0,9183.00

In [11]:
df_sctrans_2019['Empenhado(R$)'] = df_sctrans_2019['Empenhado(R$)'].apply(tratar_valores)
df_sctrans_2019['Pago(R$)'] = df_sctrans_2019['Pago(R$)'].apply(tratar_valores)
df_sctrans_2019['Liquidado(R$)'] = df_sctrans_2019['Liquidado(R$)'].apply(tratar_valores)
df_sctrans_2019['Saldo(R$)'] = df_sctrans_2019['Saldo(R$)'].apply(tratar_valores)

df_sctrans_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$)
0,79,1,03/01/2019,FIUZA CORDEIRO CONSULTORIA AUDITORIA E ASSESSO...,11.516.881/0001-14,1500.00,1500.00,1500.00,0
1,74,2,04/01/2019,JOSE INALDO DE LIRA - ME MADEREIRA PIRANHENSE ...,10.752.764/0001-97,980,980,980,0
2,79,3,07/01/2019,MOISES RODRIGUES DA SILVA,12.761.023/0001-06,500,500,500,0
3,74,4,09/01/2019,ELETRO PECAS SA LTDA,40.982.464/0001-65,110,110,110,0
4,83,5,09/01/2019,OI FIXO - TELEMAR NORTE LESTE S/A,33.000.118/0012-21,162.18,162.18,162.18,0
...,...,...,...,...,...,...,...,...,...
793,71,808,30/12/2019,IPAM - INSTITUTO DE PREVIDENCIA E ASSISTENCIA ...,12.724.464/0001-20,4359.36,4359.36,4359.36,0
794,71,809,30/12/2019,IPAM - INSTITUTO DE PREVIDENCIA E ASSISTENCIA ...,12.724.464/0001-20,8026.92,8026.92,8026.92,0
795,71,810,30/12/2019,IPAM - INSTITUTO DE PREVIDENCIA E ASSISTENCIA ...,12.724.464/0001-20,4315.05,4315.05,0,4315.05
796,66,811,30/12/2019,INSS - INSTITUTO NACIONAL DO SEGURO SOCIAL,29.979.036/0169-00,2412.89,2412.89,0,2412.89
797,74,812,30/12/2019,J. V. COMERCIO DE DERIVADOS DE PETROLEO LTDA,30.733.130/0001-02,4143.86,4143.86,0,4143.86

## Salvando dados tratados

In [12]:
df_instituto_previdencia_2019.to_csv('03_dados_tratados/dados_instituto_previdencia_2019_tratados.csv', index=False, sep=';')
df_prefeitura_2019.to_csv('03_dados_tratados/dados_prefeitura_2019_tratados.csv', index=False, sep=';')
df_sctrans_2019.to_csv('03_dados_tratados/dados_sctrans_2019_tratados.csv', index=False, sep=';')
df_camara_2019.to_csv('03_dados_tratados/dados_camara_2019_tratados.csv', index=False, sep=';')

## Analisando dados contidos nos dataframes

In [13]:
df_prefeitura_2019['Tipo'] = 1
df_instituto_previdencia_2019['Tipo'] = 2
df_sctrans_2019['Tipo'] = 3
df_camara_2019['Tipo'] = 4

In [14]:
df_dados_acumulados_2019 = pd.merge(df_prefeitura_2019, df_instituto_previdencia_2019, how='outer')
df_dados_acumulados_2019 = pd.merge(df_dados_acumulados_2019, df_sctrans_2019, how='outer')
df_dados_acumulados_2019 = pd.merge(df_dados_acumulados_2019, df_camara_2019, how='outer')
df_dados_acumulados_2019

,Despesa,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$),Tipo
0,954,18,02/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,30000.00,27358.10,27358.10,2641.90,1
1,1042,27,02/01/2019,ELIANE DO NASCIMENTO CAMPOS,13.094.898/0001-56,2032.00,2032.00,2032.00,0,1
2,922,65,07/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,75.82,75.82,75.82,0,1
3,922,68,07/01/2019,MAXICASA COMERCIO CONSTRUCOES E SERVICOS LTDA....,03.278.968/0001-72,0,0,0,0,1
4,935,94,21/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,153.66,153.66,153.66,0,1
...,...,...,...,...,...,...,...,...,...,...
8304,18,72,31/12/2019,Marcos Helder,646.603.624-34,1600.00,1600.00,1600.00,0,4
8305,19,73,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,49409.81,49409.81,49409.81,0,4
8306,20,74,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,2800.00,2800.00,2800.00,0,4
8307,28,76,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,30257.04,30257.04,30257.04,0,4
8308,26,77,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,134239.06,134239.06,134239.06,0,4

In [15]:
df_dados_acumulados_2019.drop('Despesa',axis=1, inplace=True)
df_dados_acumulados_2019

,Número,Data,Nome,CPF/CNPJ,Empenhado(R$),Liquidado(R$),Pago(R$),Saldo(R$),Tipo
0,18,02/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,30000.00,27358.10,27358.10,2641.90,1
1,27,02/01/2019,ELIANE DO NASCIMENTO CAMPOS,13.094.898/0001-56,2032.00,2032.00,2032.00,0,1
2,65,07/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,75.82,75.82,75.82,0,1
3,68,07/01/2019,MAXICASA COMERCIO CONSTRUCOES E SERVICOS LTDA....,03.278.968/0001-72,0,0,0,0,1
4,94,21/01/2019,CAGEPA-COM DE AGUA E ESGOTOS DA PARAIBA,09.123.654/0001-87,153.66,153.66,153.66,0,1
...,...,...,...,...,...,...,...,...,...
8304,72,31/12/2019,Marcos Helder,646.603.624-34,1600.00,1600.00,1600.00,0,4
8305,73,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,49409.81,49409.81,49409.81,0,4
8306,74,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,2800.00,2800.00,2800.00,0,4
8307,76,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,30257.04,30257.04,30257.04,0,4
8308,77,31/12/2019,PREFEITURA MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,134239.06,134239.06,134239.06,0,4

In [16]:
df_dados_acumulados_2019.to_csv('04_analise_tratamento_carga/dados_acumulados_2019.csv', index=False, sep=';')