# Import e tratamento dos dados

## Import de dados

In [1]:
import pandas as pd
import chardet

In [2]:
with open("02_dados_pre_tratados/dados_camara_municipal_2022.csv", "rb") as f:
    result = chardet.detect(f.read())

df_camara_2022 = pd.read_csv("02_dados_pre_tratados/dados_camara_municipal_2022.csv", sep=";", encoding=result['encoding'])
df_camara_2022

,NUMERO,DATA,ORGAO,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,476,26/12/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,09/01/2023,950,950,950,0
1,475,26/12/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,09/01/2023,"2.500,00","2.500,00","2.500,00",0
2,474,26/12/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,09/01/2023,"2.000,00","2.000,00","2.000,00",0
3,473,26/12/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,09/01/2023,"1.200,00","1.200,00","1.200,00",0
4,472,21/12/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,29/12/2022,"178,44","178,44","178,44",0
...,...,...,...,...,...,...,...,...,...
470,5,17/01/2022,01010 - Câmara Municipal,319011 - Vencimentos e Vantagens Fixas - Pesso...,24/01/2022,"31.400,00","31.400,00","31.400,00",0
471,4,17/01/2022,01010 - Câmara Municipal,319011 - Vencimentos e Vantagens Fixas - Pesso...,24/01/2022,"29.228,80","29.228,80","29.228,80",0
472,3,17/01/2022,01010 - Câmara Municipal,319011 - Vencimentos e Vantagens Fixas - Pesso...,24/01/2022,"154.920,00","154.920,00","154.920,00",0
473,2,03/01/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,20/01/2022,"4.000,00","3.360,24","3.360,24","474,76"
474,1,03/01/2022,01010 - Câmara Municipal,339039 - Outros Serviços de Terceiros - Pessoa...,20/01/2022,"4.000,00","2.198,75","2.198,75","310,2"

In [3]:
df_fundo_municipal_saude_2022 = pd.read_csv("02_dados_pre_tratados/dados_fundo_municipal_saude_2022.csv", sep=";", encoding=result['encoding'])
df_fundo_municipal_saude_2022

,NUMERO,DATA,ORGAO,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,2277,30/12/2022,02130 - Fundo Municipal de Saúde,339030 - Material de Consumo,24/02/2023,"22.970,00","22.970,00",0,"22.970,00"
1,2276,30/12/2022,02130 - Fundo Municipal de Saúde,339030 - Material de Consumo,24/02/2023,"3.842,60",0,0,"3.842,60"
2,2275,30/12/2022,02130 - Fundo Municipal de Saúde,339030 - Material de Consumo,24/02/2023,"17.920,75",0,0,"17.920,75"
3,2274,30/12/2022,02130 - Fundo Municipal de Saúde,339030 - Material de Consumo,24/02/2023,"23.333,43",0,0,"23.333,43"
4,2273,30/12/2022,02130 - Fundo Municipal de Saúde,339030 - Material de Consumo,24/02/2023,"25.673,02",0,0,"25.673,02"
...,...,...,...,...,...,...,...,...,...
1900,5,10/01/2022,02130 - Fundo Municipal de Saúde,339036 - Outros Serviços de Terceiros - Pessoa...,29/04/2022,100,100,100,0
1901,4,10/01/2022,02130 - Fundo Municipal de Saúde,339039 - Outros Serviços de Terceiros - Pessoa...,29/04/2022,"936,65","936,65","936,65",0
1902,3,10/01/2022,02130 - Fundo Municipal de Saúde,339039 - Outros Serviços de Terceiros - Pessoa...,29/04/2022,"6.156,00","6.156,00","6.156,00",0
1903,2,10/01/2022,02130 - Fundo Municipal de Saúde,339039 - Outros Serviços de Terceiros - Pessoa...,29/04/2022,"1.300,00","1.300,00","1.300,00",0
1904,1,10/01/2022,02130 - Fundo Municipal de Saúde,339092 - Despesas de Exercícios Anteriores,29/04/2022,"7.800,00","7.800,00","7.800,00",0

In [4]:
df_instituto_previdencia_2022 = pd.read_csv("02_dados_pre_tratados/dados_instituto_previdencia_2022.csv", sep=";", encoding=result['encoding'])
df_instituto_previdencia_2022

,NUMERO,DATA,ORGAO,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,254,29/12/2022,02031 - Instituto de Previdência e Assistência...,319003 - Pensões do RPPS e do militar,09/01/2023,"30.130,92","30.130,92","30.130,92",0
1,253,29/12/2022,02031 - Instituto de Previdência e Assistência...,"319001 - Aposentadorias do RPPS, Reserva Remun...",09/01/2023,"2.786,33","2.786,33","2.786,33",0
2,252,29/12/2022,02031 - Instituto de Previdência e Assistência...,"319001 - Aposentadorias do RPPS, Reserva Remun...",09/01/2023,"49.602,40","49.602,40","49.602,40",0
3,251,29/12/2022,02031 - Instituto de Previdência e Assistência...,319003 - Pensões do RPPS e do militar,09/01/2023,"168.747,17","168.747,17","167.535,17","1.212,00"
4,250,29/12/2022,02031 - Instituto de Previdência e Assistência...,"319001 - Aposentadorias do RPPS, Reserva Remun...",09/01/2023,"1.646.200,71","1.646.200,71","1.643.776,71","2.424,00"
...,...,...,...,...,...,...,...,...,...
244,5,03/01/2022,02031 - Instituto de Previdência e Assistência...,339030 - Material de Consumo,18/01/2022,35,35,35,0
245,4,03/01/2022,02031 - Instituto de Previdência e Assistência...,339030 - Material de Consumo,18/01/2022,"218,31","218,31","218,31",0
246,3,03/01/2022,02031 - Instituto de Previdência e Assistência...,339030 - Material de Consumo,18/01/2022,"176,72","176,72","176,72",0
247,2,03/01/2022,02031 - Instituto de Previdência e Assistência...,339039 - Outros Serviços de Terceiros - Pessoa...,18/01/2022,300,"91,5","75,75","224,25"
248,1,03/01/2022,02031 - Instituto de Previdência e Assistência...,339039 - Outros Serviços de Terceiros - Pessoa...,18/01/2022,"3.000,00","2.176,81","2.176,81","823,19"

In [5]:
df_prefeitura_2022 = pd.read_csv("02_dados_pre_tratados/dados_prefeitura_municipal_2022.csv", sep=";", encoding=result['encoding'])
df_prefeitura_2022

,NUMERO,DATA,ORGAO,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,40509,29/12/2022,02140 - Fundo Municipal de Assistência Social,339030 - Material de Consumo,09/01/2023,"9.538,85",0,0,"9.538,85"
1,40508,29/12/2022,02140 - Fundo Municipal de Assistência Social,339030 - Material de Consumo,09/01/2023,"8.010,40",0,0,"8.010,40"
2,7521,29/12/2022,02040 - Secretaria Municipal da Fazenda Pública,339039 - Outros Serviços de Terceiros - Pessoa...,09/01/2023,"166,36","166,36","166,36",0
3,7520,29/12/2022,02090 - Secretaria Municipal de Educação,449052 - Equipamentos e Material Permanente,09/01/2023,"63.000,00",0,0,"63.000,00"
4,7519,29/12/2022,02090 - Secretaria Municipal de Educação,339030 - Material de Consumo,09/01/2023,"3.640,80",0,"3.640,80",0
...,...,...,...,...,...,...,...,...,...
7630,5,03/01/2022,02030 - Secretaria Municipal de Administração,339092 - Despesas de Exercícios Anteriores,20/01/2022,"1.529,47","1.529,47","1.529,47",0
7631,4,03/01/2022,02030 - Secretaria Municipal de Administração,339092 - Despesas de Exercícios Anteriores,20/01/2022,"239,74","239,74","239,74",0
7632,3,03/01/2022,02030 - Secretaria Municipal de Administração,339092 - Despesas de Exercícios Anteriores,20/01/2022,"618,33","618,33","618,33",0
7633,2,03/01/2022,02030 - Secretaria Municipal de Administração,339092 - Despesas de Exercícios Anteriores,20/01/2022,"1.751,94","1.751,94","1.751,94",0
7634,1,03/01/2022,02030 - Secretaria Municipal de Administração,339092 - Despesas de Exercícios Anteriores,20/01/2022,"1.308,75","1.308,75","1.308,75",0

In [6]:
df_sctrans_2022 = pd.read_csv("02_dados_pre_tratados/dados_sctrans_2022.csv", sep=";", encoding=result['encoding'])
df_sctrans_2022

,NUMERO,DATA,ORGAO,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,730,29/12/2022,02011 - Superintendência Cajazeirense de Trânsito,469071 - Principal da Dívida Contratual Resgatado,03/01/2023,"1.234,26","1.234,26","1.234,26",0
1,729,29/12/2022,02011 - Superintendência Cajazeirense de Trânsito,469071 - Principal da Dívida Contratual Resgatado,03/01/2023,"551,1","551,1","551,1",0
2,728,29/12/2022,02011 - Superintendência Cajazeirense de Trânsito,339039 - Outros Serviços de Terceiros - Pessoa...,03/01/2023,"0,26","0,26","0,26",0
3,727,28/12/2022,02011 - Superintendência Cajazeirense de Trânsito,339030 - Material de Consumo,29/12/2022,"10.921,00","10.921,00","10.921,00",0
4,725,26/12/2022,02011 - Superintendência Cajazeirense de Trânsito,339039 - Outros Serviços de Terceiros - Pessoa...,27/12/2022,"6.396,96","6.396,96","6.396,96",0
...,...,...,...,...,...,...,...,...,...
725,5,05/01/2022,02011 - Superintendência Cajazeirense de Trânsito,339030 - Material de Consumo,19/01/2022,"1.520,00","1.520,00","1.520,00",0
726,4,05/01/2022,02011 - Superintendência Cajazeirense de Trânsito,339030 - Material de Consumo,19/01/2022,425,425,425,0
727,3,04/01/2022,02011 - Superintendência Cajazeirense de Trânsito,339039 - Outros Serviços de Terceiros - Pessoa...,19/01/2022,"1.000,00","1.000,00","1.000,00",0
728,2,03/01/2022,02011 - Superintendência Cajazeirense de Trânsito,339039 - Outros Serviços de Terceiros - Pessoa...,19/01/2022,"2.500,00","2.345,90","2.345,90",0
729,1,03/01/2022,02011 - Superintendência Cajazeirense de Trânsito,339039 - Outros Serviços de Terceiros - Pessoa...,19/01/2022,"5.000,00","5.000,00","5.000,00",0

## Tratamento dos DataFrames

In [7]:
# Definindo tipos das colunas antes de ler o dataset
columns_types = {'VALOR':float,
                'LIQUIDADO':float,
                'PAGO':float,
                'SALDO':float}

In [8]:
columns_Titles = ['NUMERO', 'DATA','CODIGO ORGAO', 'ORGAO', 'CODIGO DESPESA', 'DESPESA', 'DATA INCLUSAO', 'VALOR', 'LIQUIDADO', 'PAGO', 'SALDO']

In [9]:
'''
Função para tratamento dos valores monetários

'''

def tratar_valores(valor):
    
    '''
        Primeiramente, procura-se a localização do ponto, que separava os milhares, e a vírgula que definia os centavos de reais.
    '''
    posicao_virgula = valor.find(',')
    posicao_ponto = valor.find('.') 
    
    '''
        Após o armazenamento das posições de cada separador, armazenava o valor em uma nova string, sem os pontos e vírgulas, 
        e encontrava a nova posição do separador, agora um ponto.
    '''
    string = ''.join(filter(str.isalnum, valor))
    nova_posicao_ponto = posicao_virgula - (len(valor) - len(string))

    '''
        Por fim, após verificar qual condição a nova string se encaixava, retornava-se a nova string com o devido tratamento.
    '''
    if len(string) == len(valor):
        return valor
    
    elif posicao_ponto != -1:        
        string = string[0:nova_posicao_ponto+1] + '.' + string[nova_posicao_ponto+1:]
        return string
    
    else:
        string = string[0:posicao_virgula] + '.' + string[posicao_virgula:]
        return string
    
    '''
        Função para separar a string que carregava o valor do código e da descrição do que cada um significava
    '''    
def tratar_df(df, column, new_column):
    '''
        Há um padrão nas strings. O código numérico vai até a possição 11, o restante é o separador, hífen, que não foi armazeando,
        e a descrição que fora armazenada na nova coluna.    
    '''
    if(column == 'ORGAO'):
        df[new_column] = df[column].str.slice(0,5)
        df[column] = df[column].str.slice(7,)
    else:
        df[new_column] = df[column].str.slice(0,7)
        df[column] = df[column].str.slice(8,)

### Tratando dados

In [10]:
tratar_df(df_camara_2022, 'ORGAO', 'CODIGO ORGAO')
tratar_df(df_camara_2022, 'DESPESA', 'CODIGO DESPESA')
df_camara_2022 = df_camara_2022.reindex(columns=columns_Titles)

df_camara_2022['VALOR'] = df_camara_2022['VALOR'].apply(tratar_valores)
df_camara_2022['LIQUIDADO'] = df_camara_2022['LIQUIDADO'].apply(tratar_valores)
df_camara_2022['PAGO'] = df_camara_2022['PAGO'].apply(tratar_valores)
df_camara_2022['SALDO'] = df_camara_2022['SALDO'].apply(tratar_valores)

df_camara_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,476,26/12/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,950,950,950,0
1,475,26/12/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,2500.00,2500.00,2500.00,0
2,474,26/12/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,2000.00,2000.00,2000.00,0
3,473,26/12/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,1200.00,1200.00,1200.00,0
4,472,21/12/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/12/2022,178.44,178.44,178.44,0
...,...,...,...,...,...,...,...,...,...,...,...
470,5,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,31400.00,31400.00,31400.00,0
471,4,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,29228.80,29228.80,29228.80,0
472,3,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,154920.00,154920.00,154920.00,0
473,2,03/01/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,20/01/2022,4000.00,3360.24,3360.24,474.76
474,1,03/01/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,20/01/2022,4000.00,2198.75,2198.75,310.2

In [11]:
tratar_df(df_fundo_municipal_saude_2022, 'ORGAO', 'CODIGO ORGAO')
tratar_df(df_fundo_municipal_saude_2022, 'DESPESA', 'CODIGO DESPESA')
df_fundo_municipal_saude_2022 = df_fundo_municipal_saude_2022.reindex(columns=columns_Titles)

df_fundo_municipal_saude_2022['VALOR'] = df_fundo_municipal_saude_2022['VALOR'].apply(tratar_valores)
df_fundo_municipal_saude_2022['LIQUIDADO'] = df_fundo_municipal_saude_2022['LIQUIDADO'].apply(tratar_valores)
df_fundo_municipal_saude_2022['PAGO'] = df_fundo_municipal_saude_2022['PAGO'].apply(tratar_valores)
df_fundo_municipal_saude_2022['SALDO'] = df_fundo_municipal_saude_2022['SALDO'].apply(tratar_valores)

df_fundo_municipal_saude_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,2277,30/12/2022,02130,Fundo Municipal de Saúde,339030,Material de Consumo,24/02/2023,22970.00,22970.00,0,22970.00
1,2276,30/12/2022,02130,Fundo Municipal de Saúde,339030,Material de Consumo,24/02/2023,3842.60,0,0,3842.60
2,2275,30/12/2022,02130,Fundo Municipal de Saúde,339030,Material de Consumo,24/02/2023,17920.75,0,0,17920.75
3,2274,30/12/2022,02130,Fundo Municipal de Saúde,339030,Material de Consumo,24/02/2023,23333.43,0,0,23333.43
4,2273,30/12/2022,02130,Fundo Municipal de Saúde,339030,Material de Consumo,24/02/2023,25673.02,0,0,25673.02
...,...,...,...,...,...,...,...,...,...,...,...
1900,5,10/01/2022,02130,Fundo Municipal de Saúde,339036,Outros Serviços de Terceiros - Pessoa Física,29/04/2022,100,100,100,0
1901,4,10/01/2022,02130,Fundo Municipal de Saúde,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/04/2022,936.65,936.65,936.65,0
1902,3,10/01/2022,02130,Fundo Municipal de Saúde,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/04/2022,6156.00,6156.00,6156.00,0
1903,2,10/01/2022,02130,Fundo Municipal de Saúde,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/04/2022,1300.00,1300.00,1300.00,0
1904,1,10/01/2022,02130,Fundo Municipal de Saúde,339092,Despesas de Exercícios Anteriores,29/04/2022,7800.00,7800.00,7800.00,0

In [12]:
tratar_df(df_instituto_previdencia_2022, 'ORGAO', 'CODIGO ORGAO')
tratar_df(df_instituto_previdencia_2022, 'DESPESA', 'CODIGO DESPESA')
df_instituto_previdencia_2022 = df_instituto_previdencia_2022.reindex(columns=columns_Titles)

df_instituto_previdencia_2022['VALOR'] = df_instituto_previdencia_2022['VALOR'].apply(tratar_valores)
df_instituto_previdencia_2022['LIQUIDADO'] = df_instituto_previdencia_2022['LIQUIDADO'].apply(tratar_valores)
df_instituto_previdencia_2022['PAGO'] = df_instituto_previdencia_2022['PAGO'].apply(tratar_valores)
df_instituto_previdencia_2022['SALDO'] = df_instituto_previdencia_2022['SALDO'].apply(tratar_valores)

df_instituto_previdencia_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,254,29/12/2022,02031,Instituto de Previdência e Assistência Munici...,319003,Pensões do RPPS e do militar,09/01/2023,30130.92,30130.92,30130.92,0
1,253,29/12/2022,02031,Instituto de Previdência e Assistência Munici...,319001,"Aposentadorias do RPPS, Reserva Remunerada e ...",09/01/2023,2786.33,2786.33,2786.33,0
2,252,29/12/2022,02031,Instituto de Previdência e Assistência Munici...,319001,"Aposentadorias do RPPS, Reserva Remunerada e ...",09/01/2023,49602.40,49602.40,49602.40,0
3,251,29/12/2022,02031,Instituto de Previdência e Assistência Munici...,319003,Pensões do RPPS e do militar,09/01/2023,168747.17,168747.17,167535.17,1212.00
4,250,29/12/2022,02031,Instituto de Previdência e Assistência Munici...,319001,"Aposentadorias do RPPS, Reserva Remunerada e ...",09/01/2023,1646200.71,1646200.71,1643776.71,2424.00
...,...,...,...,...,...,...,...,...,...,...,...
244,5,03/01/2022,02031,Instituto de Previdência e Assistência Munici...,339030,Material de Consumo,18/01/2022,35,35,35,0
245,4,03/01/2022,02031,Instituto de Previdência e Assistência Munici...,339030,Material de Consumo,18/01/2022,218.31,218.31,218.31,0
246,3,03/01/2022,02031,Instituto de Previdência e Assistência Munici...,339030,Material de Consumo,18/01/2022,176.72,176.72,176.72,0
247,2,03/01/2022,02031,Instituto de Previdência e Assistência Munici...,339039,Outros Serviços de Terceiros - Pessoa Jurídica,18/01/2022,300,91.5,75.75,224.25
248,1,03/01/2022,02031,Instituto de Previdência e Assistência Munici...,339039,Outros Serviços de Terceiros - Pessoa Jurídica,18/01/2022,3000.00,2176.81,2176.81,823.19

In [13]:
tratar_df(df_prefeitura_2022, 'ORGAO', 'CODIGO ORGAO')
tratar_df(df_prefeitura_2022, 'DESPESA', 'CODIGO DESPESA')
df_prefeitura_2022 = df_prefeitura_2022.reindex(columns=columns_Titles)

df_prefeitura_2022['VALOR'] = df_prefeitura_2022['VALOR'].apply(tratar_valores)
df_prefeitura_2022['LIQUIDADO'] = df_prefeitura_2022['LIQUIDADO'].apply(tratar_valores)
df_prefeitura_2022['PAGO'] = df_prefeitura_2022['PAGO'].apply(tratar_valores)
df_prefeitura_2022['SALDO'] = df_prefeitura_2022['SALDO'].apply(tratar_valores)

df_prefeitura_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,40509,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,9538.85,0,0,9538.85
1,40508,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,8010.40,0,0,8010.40
2,7521,29/12/2022,02040,Secretaria Municipal da Fazenda Pública,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,166.36,166.36,166.36,0
3,7520,29/12/2022,02090,Secretaria Municipal de Educação,449052,Equipamentos e Material Permanente,09/01/2023,63000.00,0,0,63000.00
4,7519,29/12/2022,02090,Secretaria Municipal de Educação,339030,Material de Consumo,09/01/2023,3640.80,0,3640.80,0
...,...,...,...,...,...,...,...,...,...,...,...
7630,5,03/01/2022,02030,Secretaria Municipal de Administração,339092,Despesas de Exercícios Anteriores,20/01/2022,1529.47,1529.47,1529.47,0
7631,4,03/01/2022,02030,Secretaria Municipal de Administração,339092,Despesas de Exercícios Anteriores,20/01/2022,239.74,239.74,239.74,0
7632,3,03/01/2022,02030,Secretaria Municipal de Administração,339092,Despesas de Exercícios Anteriores,20/01/2022,618.33,618.33,618.33,0
7633,2,03/01/2022,02030,Secretaria Municipal de Administração,339092,Despesas de Exercícios Anteriores,20/01/2022,1751.94,1751.94,1751.94,0
7634,1,03/01/2022,02030,Secretaria Municipal de Administração,339092,Despesas de Exercícios Anteriores,20/01/2022,1308.75,1308.75,1308.75,0

In [14]:
tratar_df(df_sctrans_2022, 'ORGAO', 'CODIGO ORGAO')
tratar_df(df_sctrans_2022, 'DESPESA', 'CODIGO DESPESA')
df_sctrans_2022 = df_sctrans_2022.reindex(columns=columns_Titles)

df_sctrans_2022['VALOR'] = df_sctrans_2022['VALOR'].apply(tratar_valores)
df_sctrans_2022['LIQUIDADO'] = df_sctrans_2022['LIQUIDADO'].apply(tratar_valores)
df_sctrans_2022['PAGO'] = df_sctrans_2022['PAGO'].apply(tratar_valores)
df_sctrans_2022['SALDO'] = df_sctrans_2022['SALDO'].apply(tratar_valores)

df_sctrans_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,730,29/12/2022,02011,Superintendência Cajazeirense de Trânsito,469071,Principal da Dívida Contratual Resgatado,03/01/2023,1234.26,1234.26,1234.26,0
1,729,29/12/2022,02011,Superintendência Cajazeirense de Trânsito,469071,Principal da Dívida Contratual Resgatado,03/01/2023,551.1,551.1,551.1,0
2,728,29/12/2022,02011,Superintendência Cajazeirense de Trânsito,339039,Outros Serviços de Terceiros - Pessoa Jurídica,03/01/2023,0.26,0.26,0.26,0
3,727,28/12/2022,02011,Superintendência Cajazeirense de Trânsito,339030,Material de Consumo,29/12/2022,10921.00,10921.00,10921.00,0
4,725,26/12/2022,02011,Superintendência Cajazeirense de Trânsito,339039,Outros Serviços de Terceiros - Pessoa Jurídica,27/12/2022,6396.96,6396.96,6396.96,0
...,...,...,...,...,...,...,...,...,...,...,...
725,5,05/01/2022,02011,Superintendência Cajazeirense de Trânsito,339030,Material de Consumo,19/01/2022,1520.00,1520.00,1520.00,0
726,4,05/01/2022,02011,Superintendência Cajazeirense de Trânsito,339030,Material de Consumo,19/01/2022,425,425,425,0
727,3,04/01/2022,02011,Superintendência Cajazeirense de Trânsito,339039,Outros Serviços de Terceiros - Pessoa Jurídica,19/01/2022,1000.00,1000.00,1000.00,0
728,2,03/01/2022,02011,Superintendência Cajazeirense de Trânsito,339039,Outros Serviços de Terceiros - Pessoa Jurídica,19/01/2022,2500.00,2345.90,2345.90,0
729,1,03/01/2022,02011,Superintendência Cajazeirense de Trânsito,339039,Outros Serviços de Terceiros - Pessoa Jurídica,19/01/2022,5000.00,5000.00,5000.00,0

## Salvando dados tratados

In [15]:
df_instituto_previdencia_2022.to_csv('03_dados_tratados/dados_instituto_previdencia_2022_tratados.csv', index=False, sep=';')
df_prefeitura_2022.to_csv('03_dados_tratados/dados_prefeitura_2022_tratados.csv', index=False, sep=';')
df_sctrans_2022.to_csv('03_dados_tratados/dados_sctrans_2022_tratados.csv', index=False, sep=';')
df_camara_2022.to_csv('03_dados_tratados/dados_camara_2022_tratados.csv', index=False, sep=';')
df_fundo_municipal_saude_2022.to_csv('03_dados_tratados/dados_fundo_municipal_saude_2022_tratados.csv', index=False, sep=';')

## Juntando todos os dados tratados em um único documento

In [16]:
df_prefeitura_fundo_saude_2022 = pd.merge(df_prefeitura_2022, df_fundo_municipal_saude_2022, how='outer')
df_prefeitura_fundo_saude_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO
0,40509,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,9538.85,0,0,9538.85
1,40508,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,8010.40,0,0,8010.40
2,7521,29/12/2022,02040,Secretaria Municipal da Fazenda Pública,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,166.36,166.36,166.36,0
3,7520,29/12/2022,02090,Secretaria Municipal de Educação,449052,Equipamentos e Material Permanente,09/01/2023,63000.00,0,0,63000.00
4,7519,29/12/2022,02090,Secretaria Municipal de Educação,339030,Material de Consumo,09/01/2023,3640.80,0,3640.80,0
...,...,...,...,...,...,...,...,...,...,...,...
9535,5,10/01/2022,02130,Fundo Municipal de Saúde,339036,Outros Serviços de Terceiros - Pessoa Física,29/04/2022,100,100,100,0
9536,4,10/01/2022,02130,Fundo Municipal de Saúde,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/04/2022,936.65,936.65,936.65,0
9537,3,10/01/2022,02130,Fundo Municipal de Saúde,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/04/2022,6156.00,6156.00,6156.00,0
9538,2,10/01/2022,02130,Fundo Municipal de Saúde,339039,Outros Serviços de Terceiros - Pessoa Jurídica,29/04/2022,1300.00,1300.00,1300.00,0
9539,1,10/01/2022,02130,Fundo Municipal de Saúde,339092,Despesas de Exercícios Anteriores,29/04/2022,7800.00,7800.00,7800.00,0

In [17]:
df_prefeitura_fundo_saude_2022.to_csv('04_analise_tratamento_carga/dados_prefeitura_fundo_saude_2022.csv', index=False, sep=';')

In [18]:
df_prefeitura_fundo_saude_2022['TIPO'] = 1
df_instituto_previdencia_2022['TIPO'] = 2
df_sctrans_2022['TIPO'] = 3
df_camara_2022['TIPO'] = 4

In [19]:
df_dados_acumulados_2022 = pd.merge(df_prefeitura_fundo_saude_2022, df_instituto_previdencia_2022, how='outer')
df_dados_acumulados_2022 = pd.merge(df_dados_acumulados_2022, df_sctrans_2022, how='outer')
df_dados_acumulados_2022 = pd.merge(df_dados_acumulados_2022, df_camara_2022, how='outer')
df_dados_acumulados_2022

,NUMERO,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO,TIPO
0,40509,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,9538.85,0,0,9538.85,1
1,40508,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,8010.40,0,0,8010.40,1
2,7521,29/12/2022,02040,Secretaria Municipal da Fazenda Pública,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,166.36,166.36,166.36,0,1
3,7520,29/12/2022,02090,Secretaria Municipal de Educação,449052,Equipamentos e Material Permanente,09/01/2023,63000.00,0,0,63000.00,1
4,7519,29/12/2022,02090,Secretaria Municipal de Educação,339030,Material de Consumo,09/01/2023,3640.80,0,3640.80,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10989,5,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,31400.00,31400.00,31400.00,0,4
10990,4,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,29228.80,29228.80,29228.80,0,4
10991,3,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,154920.00,154920.00,154920.00,0,4
10992,2,03/01/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,20/01/2022,4000.00,3360.24,3360.24,474.76,4
10993,1,03/01/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,20/01/2022,4000.00,2198.75,2198.75,310.2,4

In [20]:
df_dados_acumulados_2022.drop('NUMERO', axis=1, inplace=True)
df_dados_acumulados_2022

,DATA,CODIGO ORGAO,ORGAO,CODIGO DESPESA,DESPESA,DATA INCLUSAO,VALOR,LIQUIDADO,PAGO,SALDO,TIPO
0,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,9538.85,0,0,9538.85,1
1,29/12/2022,02140,Fundo Municipal de Assistência Social,339030,Material de Consumo,09/01/2023,8010.40,0,0,8010.40,1
2,29/12/2022,02040,Secretaria Municipal da Fazenda Pública,339039,Outros Serviços de Terceiros - Pessoa Jurídica,09/01/2023,166.36,166.36,166.36,0,1
3,29/12/2022,02090,Secretaria Municipal de Educação,449052,Equipamentos e Material Permanente,09/01/2023,63000.00,0,0,63000.00,1
4,29/12/2022,02090,Secretaria Municipal de Educação,339030,Material de Consumo,09/01/2023,3640.80,0,3640.80,0,1
...,...,...,...,...,...,...,...,...,...,...,...
10989,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,31400.00,31400.00,31400.00,0,4
10990,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,29228.80,29228.80,29228.80,0,4
10991,17/01/2022,01010,Câmara Municipal,319011,Vencimentos e Vantagens Fixas - Pessoal Civil,24/01/2022,154920.00,154920.00,154920.00,0,4
10992,03/01/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,20/01/2022,4000.00,3360.24,3360.24,474.76,4
10993,03/01/2022,01010,Câmara Municipal,339039,Outros Serviços de Terceiros - Pessoa Jurídica,20/01/2022,4000.00,2198.75,2198.75,310.2,4

In [21]:
df_dados_acumulados_2022.to_csv('04_analise_tratamento_carga/dados_acumulados_2022.csv', index=False, sep=';')