# Imports necessários

In [1]:
import string
import pandas as pd
from unidecode import unidecode
import re
from random import randint
import requests
import numpy as np
import os
import csv
import uuid

# Caminho para import dos dados

In [2]:
# Definir uma variável global para armazenar as informações lidas do arquivo
linhas = []

# Definir uma variável de ambiente para armazenar a localização do arquivo
os.environ['PATHS'] = 'receitas.env'

# Função para ler as informações do arquivo e adicioná-las à variável global
def ler_arquivo():
    global linhas
    with open(os.environ.get('PATHS'), 'r') as f:
        linhas = [linha.strip().split(',') for linha in f.readlines()]

# Chamar a função para ler o arquivo e atualizar a variável global
ler_arquivo()

# Imprimir a variável global
print(linhas)

[['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2013/04_analise_tratamento_carga/dados_acumulados_2013.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2014/04_analise_tratamento_carga/dados_acumulados_2014.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2015/04_analise_tratamento_carga/dados_acumulados_2015.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2016/04_analise_tratamento_carga/dados_acumulados_2016.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2017/04_analise_tratamento_carga/dados_acumulados_2017.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2018/04_analise_tratamento_carga/dados_acumulados_2018.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2019/04_analise_tratamento_carga/dados_acumulados_2019.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2020/04_analise_tratamento_carga/dados_acumulados_2020.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2021/04_analise_tratamento_carga/dados_acumulados_2021.csv'], ['C:/Users/allys/Dados_TCC/dw_contas_publicas_2022/TCC2/dados/01_receitas/2022/04_analise_tratamento_carga/dados_acumulados_2022.csv']]

## Definindo parâmetros para salvar o arquivo .csv

In [3]:
# definir parâmetros do arquivo CSV
csv_kwargs = {'index': False,
              'sep': ';',
              'quoting': csv.QUOTE_NONE,
              'quotechar': '"'}

## Função para salvar df

In [4]:
def save_dataframe(df, filename):
    # Verifica se o diretório existe e cria caso não exista
    diretorio = './arquivos_para_carga'
    if not os.path.exists(diretorio):
        os.makedirs(diretorio)
    
    # Salva o dataframe em um arquivo csv no diretório criado
    filepath = f'./{diretorio}/{filename}.csv'
    df.to_csv(filepath, index=False, sep=';')

# Receitas

## Importando dados

### Lista com os df

In [5]:
list_data_frames = []

def inserir_df(df):
    list_data_frames.append(df)

In [6]:
df_receitas_2013 = pd.read_csv(linhas[0][0], sep=';')
inserir_df(df_receitas_2013)

df_receitas_2014 = pd.read_csv(linhas[1][0], sep=';')
inserir_df(df_receitas_2014)

df_receitas_2015 = pd.read_csv(linhas[2][0], sep=';')
inserir_df(df_receitas_2015)

df_receitas_2016 = pd.read_csv(linhas[3][0], sep=';')
inserir_df(df_receitas_2016)

df_receitas_2017 = pd.read_csv(linhas[4][0], sep=';')
inserir_df(df_receitas_2017)

df_receitas_2018 = pd.read_csv(linhas[5][0], sep=';')
inserir_df(df_receitas_2018)

df_receitas_2019 = pd.read_csv(linhas[6][0], sep=';')
inserir_df(df_receitas_2019)

df_receitas_2020 = pd.read_csv(linhas[7][0], sep=';')
inserir_df(df_receitas_2020)

df_receitas_2021 = pd.read_csv(linhas[8][0], sep=';')
inserir_df(df_receitas_2021)

df_receitas_2022 = pd.read_csv(linhas[9][0], sep=';')
inserir_df(df_receitas_2022)

### Padronizando os df para junção

In [7]:
dic_renomear_colunas = {'Código':'CODIGO',
                        'Receita':'RECEITA',
                        'Data':'DATA',
                        'Nome':'CONTRIBUINTE',
                        'FORNECEDOR':'CONTRIBUINTE',
                        'Valor Previsto':'VALOR PREVISTO',
                        'Valor Arrecadado': 'VALOR ARRECADADO',
                        'VALOR': 'VALOR ARRECADADO',
                        'Tipo':'TIPO'}

def renomear_colunas(df):
    df.rename(columns=dic_renomear_colunas, inplace=True)
    
for df in list_data_frames:
    renomear_colunas(df)

In [8]:
dados_2020 = ['CODIGO','RECEITA','DATA','CONTRIBUINTE','CPF/CNPJ','VALOR PREVISTO','VALOR ARRECADADO','TIPO']
dados_2022 = ['CODIGO','RECEITA','DATA','CONTRIBUINTE','VALOR ARRECADADO','TIPO']

df_dados_completos_2020 = pd.DataFrame(columns=dados_2020)
df_dados_completos_2022 = pd.DataFrame(columns=dados_2022)

### Merge Dfs

In [9]:
def merge_dataframes(lista_dataframes, colunas_sem_valores):
    
    df_final = colunas_sem_valores.copy() # cria uma cópia do DataFrame das colunas sem valores
    
    for df in lista_dataframes:
        df_final = pd.merge(df_final, df, on=list(df_final.columns), how='outer') # mescla o DataFrame atual com o DataFrame das colunas
        
    return df_final

In [10]:
def remove_espacos_duplos(df):
    # copia o DataFrame original
    df_copy = df.copy()
    # itera sobre as colunas do DataFrame
    for col in df_copy.columns:
        # verifica se a coluna é do tipo 'object' (string)
        if df_copy[col].dtype == 'O':
            # remove espaços duplicados da coluna
            df_copy[col] = df_copy[col].str.replace('\s+', ' ')
    return df_copy

In [11]:
df_dados_completos_2020 = merge_dataframes(list_data_frames[:8],df_dados_completos_2020)
df_dados_completos_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO
0,1722010101,COTA-PARTE DO ICMS,03/01/2013,PREF MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,8362000.0,185560.68,1
1,1722010101,COTA-PARTE DO ICMS,04/01/2013,PREF MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,8362000.0,8081.80,1
2,1722010101,COTA-PARTE DO ICMS,07/01/2013,PREF MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,8362000.0,4231.39,1
3,1722010101,COTA-PARTE DO ICMS,08/01/2013,PREF MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,8362000.0,10536.53,1
4,1722010101,COTA-PARTE DO ICMS,15/01/2013,PREF MUNICIPAL DE CAJAZEIRAS,08.923.971/0001-15,8362000.0,103118.27,1

In [12]:
df_dados_completos_2022 = merge_dataframes(list_data_frames[8:],df_dados_completos_2022)
df_dados_completos_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO
0,175801111,Transferências de Recursos do Fundo de Manute...,01/12/2021,BANCO DO BRASIL S.A,6224.78,1
1,132100111,Remuneração de Depósitos Bancários - Principal,01/12/2021,BANCO DO BRASIL SA,-6224.78,1
2,175801111,Transferências de Recursos do Fundo de Manute...,01/12/2021,BANCO DO BRASIL S.A,722577.64,1
3,171809111,Transferências de Recursos da Complementação ...,01/12/2021,BANCO DO BRASIL SA,-722577.64,1
4,175801111,Transferências de Recursos do Fundo de Manute...,01/12/2021,BANCO DO BRASIL S.A,1166975.68,1

### Tratamento valores das colunas - Retirando pontuação e acentuação

In [13]:
def tratar_coluna(df, coluna):
    
    # remove sinais de pontuação e símbolos
    table = str.maketrans('', '', string.punctuation)
    df[coluna] = df[coluna].apply(lambda x: str(x).translate(table))
    
    # remove acentuação gráfica
    df[coluna] = df[coluna].apply(lambda x: unidecode(x))
    
    # converte todos os caracteres para minúsculas
    df[coluna] = df[coluna].str.lower()
    
    return df

In [14]:
df_dados_completos_tratados_2020 = tratar_coluna(df_dados_completos_2020, 'RECEITA')
df_dados_completos_tratados_2020 = tratar_coluna(df_dados_completos_2020, 'CONTRIBUINTE')
df_dados_completos_tratados_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO
0,1722010101,cotaparte do icms,03/01/2013,pref municipal de cajazeiras,08.923.971/0001-15,8362000.0,185560.68,1
1,1722010101,cotaparte do icms,04/01/2013,pref municipal de cajazeiras,08.923.971/0001-15,8362000.0,8081.80,1
2,1722010101,cotaparte do icms,07/01/2013,pref municipal de cajazeiras,08.923.971/0001-15,8362000.0,4231.39,1
3,1722010101,cotaparte do icms,08/01/2013,pref municipal de cajazeiras,08.923.971/0001-15,8362000.0,10536.53,1
4,1722010101,cotaparte do icms,15/01/2013,pref municipal de cajazeiras,08.923.971/0001-15,8362000.0,103118.27,1

In [15]:
df_dados_completos_tratados_2022 = tratar_coluna(df_dados_completos_2022, 'RECEITA')
df_dados_completos_tratados_2022 = tratar_coluna(df_dados_completos_2022, 'CONTRIBUINTE')
df_dados_completos_tratados_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO
0,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,6224.78,1
1,132100111,remuneracao de depositos bancarios principal,01/12/2021,banco do brasil sa,-6224.78,1
2,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,722577.64,1
3,171809111,transferencias de recursos da complementacao ...,01/12/2021,banco do brasil sa,-722577.64,1
4,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,1166975.68,1

## Criando coluna do Código único de cada contribuinte

### Padronizando dados da coluna contribuinte dos df de 2013 - 2020

In [16]:
dic_padronizar_valores = {'pref municipal de cajazeiras':'prefeitura municipal de cajazeiras',
                          'camara municipal de cajazeiras':'camara municipal de cajazeiras',
                          'municipio de cajazeiras fundo municipal de saude  fms':'fundo municipal de saude de cajazeiras',
                          'instituto de previdencia e assistencia municipal de cajazeiras':'instituto de previdencia e assistencia municipal'}

In [17]:
def padroniza_contribuintes(df, dicionario, coluna):
    # Cria um novo DataFrame para evitar perda de dados do antigo
    novo_df = df.copy()
    
    # Para cada chave no dicionário, encontra as linhas do DataFrame em que o valor na coluna especificada corresponde à chave
    for chave in dicionario:
        novo_df.loc[novo_df[coluna] == chave, coluna] = dicionario[chave]
        
    return novo_df

In [18]:
df_dados_completos_tratados_2020 = padroniza_contribuintes(df_dados_completos_tratados_2020, dic_padronizar_valores, 'CONTRIBUINTE')
df_dados_completos_tratados_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO
0,1722010101,cotaparte do icms,03/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,185560.68,1
1,1722010101,cotaparte do icms,04/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,8081.80,1
2,1722010101,cotaparte do icms,07/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,4231.39,1
3,1722010101,cotaparte do icms,08/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,10536.53,1
4,1722010101,cotaparte do icms,15/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,103118.27,1

### Limpando a coluna contribuinte e criando a coluna CPF/CNPJ dos df de 2021 - 2022

In [19]:
def extrair_cpf_cnpj(df):
    # Expressão regular para identificar sequências de números com mais de 5 dígitos
    regex = r'\d{6,}'
    
    # Criando um novo dataframe para evitar perdas no original
    new_df = df.copy()
    
    # Verifica se a coluna 'CPF/CNPJ' já existe, caso contrário, cria a coluna
    if 'CPF/CNPJ' not in new_df.columns:
        new_df['CPF/CNPJ'] = ''
    
    # Iteração sobre cada linha do novo dataframe
    for i, row in new_df.iterrows():
        # Busca por padrões numéricos na coluna 'CONTRIBUINTE' usando regex
        matches = re.findall(regex, row['CONTRIBUINTE'])
        
        # Se encontrou algum padrão, assume que é um CPF/CNPJ e extrai a primeira ocorrência
        if matches:
            cpf_cnpj = matches[0]
            
            # Remove a sequência de CPF/CNPJ da coluna 'CONTRIBUINTE'
            contribuintes = row['CONTRIBUINTE'].replace(cpf_cnpj, '')
            new_df.at[i, 'CONTRIBUINTE'] = contribuintes
            
            # Armazena o CPF/CNPJ na coluna 'CPF/CNPJ'
            new_df.at[i, 'CPF/CNPJ'] = formatar_cpf_cnpj(cpf_cnpj)
    
    return new_df

def formatar_cpf_cnpj(cpf_cnpj):
    # Verifica o tamanho da string e formata para o tipo correspondente
    if len(cpf_cnpj) == 11:
        cpf_cnpj_formatado = f'{cpf_cnpj[:3]}.{cpf_cnpj[3:6]}.{cpf_cnpj[6:9]}-{cpf_cnpj[9:]}'
    elif len(cpf_cnpj) == 14:
        cpf_cnpj_formatado = f'{cpf_cnpj[:2]}.{cpf_cnpj[2:5]}.{cpf_cnpj[5:8]}/{cpf_cnpj[8:12]}-{cpf_cnpj[12:]}'
    else:
        # Caso a string não seja do tamanho esperado, mantém o valor original
        cpf_cnpj_formatado = cpf_cnpj

    # Retorna a string formatada
    return cpf_cnpj_formatado

In [20]:
df_dados_completos_tratados_2022 = extrair_cpf_cnpj(df_dados_completos_tratados_2022)
df_dados_completos_tratados_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO,CPF/CNPJ
0,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,6224.78,1,
1,132100111,remuneracao de depositos bancarios principal,01/12/2021,banco do brasil sa,-6224.78,1,
2,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,722577.64,1,
3,171809111,transferencias de recursos da complementacao ...,01/12/2021,banco do brasil sa,-722577.64,1,
4,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,1166975.68,1,

### Preechendo células vazias

In [21]:
def preenche_celulas_vazias(df, column, fill_string):
    # Verifica se a coluna especificada está presente no dataframe
    if column not in df.columns:
        print(f"Coluna {column} não encontrada no dataframe!")
        return df
    
    # Cria uma cópia do dataframe para evitar a perda dos dados originais
    df_novo = df.copy()

    # Preenche células vazias na coluna 'CPF/CNPJ' com a mensagem 'nao ha registro do documento original'
    df_novo[column].fillna(fill_string, inplace=True)

    # Preenche células vazias na coluna 'CPF/CNPJ' com a mensagem 'nao ha registro do documento original'
    df_novo[column].replace('', fill_string, inplace=True)

    return df_novo

In [22]:
df_dados_completos_tratados_2022 = preenche_celulas_vazias(df_dados_completos_tratados_2022,'CPF/CNPJ','sem informacao')
df_dados_completos_tratados_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO,CPF/CNPJ
0,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,6224.78,1,sem informacao
1,132100111,remuneracao de depositos bancarios principal,01/12/2021,banco do brasil sa,-6224.78,1,sem informacao
2,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,722577.64,1,sem informacao
3,171809111,transferencias de recursos da complementacao ...,01/12/2021,banco do brasil sa,-722577.64,1,sem informacao
4,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,1166975.68,1,sem informacao

In [23]:
df_dados_completos_tratados_2020 = preenche_celulas_vazias(df_dados_completos_tratados_2020,'CPF/CNPJ','sem informacao')
df_dados_completos_tratados_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO
0,1722010101,cotaparte do icms,03/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,185560.68,1
1,1722010101,cotaparte do icms,04/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,8081.80,1
2,1722010101,cotaparte do icms,07/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,4231.39,1
3,1722010101,cotaparte do icms,08/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,10536.53,1
4,1722010101,cotaparte do icms,15/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,103118.27,1

### Criação da coluna única do código

In [24]:
def df_to_dict(df, coluna_chave, coluna_valor,coluna_agrupadora):
    """
    Converte duas colunas de um DataFrame em um dicionário.

    Args:
        df (pandas.DataFrame): DataFrame contendo as colunas a serem convertidas.
        coluna_chave (str): Nome da coluna a ser usada como chave do dicionário.
        coluna_valor (str): Nome da coluna a ser usada como valor do dicionário.
        coluna_agrupadora (str): Nome da coluna a ser usada como coluna agrupadora.

    Returns:
        dict: Dicionário com os valores das colunas especificadas.
    """

    # Cria um dicionário vazio
    dicionario = {}
    
    # Agrupa os dados por tipo
    grupos = df.groupby(coluna_agrupadora)

    # Percorre cada grupo e adiciona a chave e valor correspondentes no dicionário
    for nome_grupo, grupo in grupos:
        # Cria um dicionário para o grupo atual
        dict_grupo = {}
        # Percorre cada linha do grupo e adiciona a chave e valor correspondentes no dicionário do grupo
        for indice, linha in grupo.iterrows():
            chave = linha[coluna_chave]
            valor = linha[coluna_valor]
            dict_grupo[chave] = valor
        # Adiciona o dicionário do grupo ao dicionário geral, usando o nome do grupo como chave
        dicionario[nome_grupo] = dict_grupo

    return dicionario

In [25]:
def merge_dataframes(df1, df2):
    
    # Cria cópias dos dataframes para evitar perda de dados
    df1_copy = df1.copy()
    df2_copy = df2.copy()
    
    # Itera sobre cada linha do primeiro dataframe
    for i, row1 in df1_copy.iterrows():
        string_comparacao = row1['CONTRIBUINTE'] + '-' + str(row1['TIPO'])
        
        # Itera sobre cada linha do segundo dataframe
        for j, row2 in df2_copy.iterrows():
            
            # Compara o valor da coluna 'CONTRIBUINTE' em ambas as linhas
            if string_comparacao == row2['CONCAT_CODIGO']:
                
                # Atribui o valor da coluna 'CPF/CNPJ' do primeiro dataframe no segundo
                df2_copy.at[j, 'CPF/CNPJ'] = row1['CPF/CNPJ']
    
    # Faz o merge dos dois dataframes sem valores duplicados
    merged_df = pd.concat([df1_copy, df2_copy]).reset_index(drop=True)
    
    return merged_df

In [26]:
import hashlib

def gerar_codigo_unico(df, coluna_parametro):
    # Cria uma cópia do dataframe apenas com as colunas necessárias para a codificação
    df_copy = df[[coluna_parametro]].copy()

    # Cria um dicionário vazio para armazenar os códigos únicos gerados
    codigos = {}

    # Percorre cada linha do dataframe e armazena o código único gerado a partir do valor da coluna_parametro
    # no dicionário de códigos, se ainda não estiver lá
    for index, row in df_copy.iterrows():
        valor = row[coluna_parametro]
        if valor not in codigos:
            # Calcula o hash MD5 do valor da coluna_parametro
            codigo_hash = hashlib.md5(str(valor).encode('utf-8')).hexdigest()

            # Pega os primeiros 14 caracteres do hash como código único
            codigo_unico = codigo_hash[:14]

            # Armazena o código único no dicionário, com a chave sendo o valor da coluna_parametro
            codigos[valor] = codigo_unico
    
    # Cria uma nova coluna CODIGO no dataframe e preenche com os códigos gerados
    df['CODIGO'] = [codigos[row[coluna_parametro]] for index, row in df_copy.iterrows()]

    # Retorna o dataframe com a nova coluna CODIGO
    return df

In [27]:
df_dados_completos_tratados_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO
0,1722010101,cotaparte do icms,03/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,185560.68,1
1,1722010101,cotaparte do icms,04/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,8081.80,1
2,1722010101,cotaparte do icms,07/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,4231.39,1
3,1722010101,cotaparte do icms,08/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,10536.53,1
4,1722010101,cotaparte do icms,15/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,103118.27,1

In [28]:
dic_valores_2020 = df_to_dict(df_dados_completos_2020,'CPF/CNPJ','TIPO','TIPO')
dic_valores_2020

{1: {'08.923.971/0001-15': 1,
  '00.360.305/0040-10': 1,
  nan: 1,
  '603.496.544-68': 1,
  '064.659.174-67': 1,
  '500.464.204-44': 1,
  '556.107.653-15': 1,
  '05.471.862/0001-16': 1,
  '10.571.183/0001-59': 1,
  '032.689.294-00': 1,
  '11.516.881/0001-14': 1,
  '029.318.644-80': 1,
  '023.536.144-50': 1,
  '010.234.594-50': 1,
  '041.750.174-96': 1,
  '646.603.704-53': 1,
  '13.317.281/0001-52': 1,
  '040.902.873-83': 1,
  '21.551.210/0001-48': 1,
  '683.446.354-20': 1,
  '048.557.104-82': 1,
  '839.469.854-91': 1,
  '042.944.264-54': 1,
  '205.852.414-49': 1,
  '014.991.164-54': 1,
  '042.526.534-01': 1,
  '034.228.554-83': 1,
  '014.795.334-08': 1,
  '060.469.154-81': 1,
  '129.373.868-90': 1,
  '097.900.524-80': 1,
  '229.721.008-67': 1,
  '058.612.444-64': 1,
  '17.691.935/0001-64': 1,
  '068.714.274-14': 1,
  '568.448.674-68': 1,
  '09.095.183/0001-40': 1,
  '14.265.552/0001-36': 1,
  '042.164.284-01': 1,
  '05.342.580/0001-19': 1,
  '11.663.900/0001-35': 1,
  '019.744.448-21': 1,
  '27.260.315/0001-24': 1,
  '951.830.434-34': 1,
  '113.372.824-30': 1,
  '084.238.754-40': 1,
  '797.248.504-63': 1,
  '047.087.944-01': 1,
  '056.092.364-36': 1,
  '04.801.728/0001-73': 1,
  '10.293.888/0001-51': 1,
  '09.353.327/0001-11': 1,
  '24.215.436/0001-66': 1,
  '11.895.653/0001-00': 1,
  '10.954.450/0001-77': 1,
  '08.170.630/0001-16': 1,
  '02.737.867/0001-50': 1,
  '029.244.903-83': 1,
  '07.671.995/0001-61': 1,
  '16.600.654/0001-96': 1,
  '13.304.347/0001-70': 1,
  '97.545.946/0001-75': 1,
  '35.568.849/0001-40': 1,
  '07.206.138/0001-90': 1,
  '07.748.243/0001-51': 1,
  '13.326.462/0001-45': 1,
  '40.953.200/0001-83': 1,
  '13.530.513/0001-56': 1,
  '05.816.614/0001-60': 1,
  '40.964.066/0001-16': 1,
  '03.434.985/0001-51': 1,
  '17.191.317/0001-55': 1,
  '08.923.815/0001-54': 1,
  '01.791.741/0001-09': 1,
  '03.538.267/0001-25': 1,
  '05.079.341/0001-18': 1,
  '01.048.873/0001-37': 1,
  '01.230.394/0001-37': 1,
  '08.605.487/0001-48': 1,
  '09.185.398/0001-52': 1,
  '11.427.407/0001-16': 1,
  '03.936.074/0002-03': 1,
  '09.238.207/0001-73': 1,
  '35.506.567/0002-08': 1,
  '10.609.902/0001-83': 1,
  '10.867.184/0001-45': 1,
  '11.118.954/0001-10': 1,
  '00.391.528/0001-39': 1,
  '04.076.245/0001-53': 1,
  '04.375.419/0001-89': 1,
  '07.202.863/0001-90': 1,
  '15.665.345/0001-31': 1,
  '119.670.114-86': 1,
  '04.763.831/0001-76': 1,
  '07.239.645/0001-20': 1,
  '03.509.150/0005-47': 1,
  '05.748.217/0001-06': 1,
  '063.190.764-53': 1,
  '15.466.280/0001-03': 1,
  '07.467.240/0001-40': 1,
  '15.626.860/0001-02': 1,
  '40.973.307/0001-93': 1,
  '03.620.255/0001-45': 1,
  '05.139.831/0001-62': 1,
  '01.326.360/0001-40': 1,
  '14.958.510/0001-80': 1,
  '06.179.688/0001-03': 1,
  '07.447.487/0001-02': 1,
  '10.997.953/0001-20': 1,
  '18.406.277/0001-84': 1,
  '41.141.599/0001-60': 1,
  '17.231.568/0001-16': 1,
  '13.250.842/0001-43': 1,
  '10.309.248/0001-92': 1,
  '023.026.234-10': 1,
  '17.952.724/0001-38': 1,
  '08.757.221/0001-10': 1,
  '05.895.220/0001-44': 1,
  '00.198.693/0001-79': 1,
  '04.696.443/0001-10': 1,
  '24.504.623/0001-60': 1,
  '00.000.000/0099-03': 1,
  '13.291.727/0001-17': 1,
  '11.180.607/0001-17': 1,
  '037.514.284-37': 1,
  '11.902.878/0001-39': 1,
  '069.698.534-97': 1,
  '12.724.464/0001-20': 1,
  '14.237.493/0001-92': 1,
  '09.472.050/0001-46': 1,
  '08.790.792/0003-19': 1,
  '02.723.169/0001-03': 1,
  '059.243.524-55': 1,
  '04.242.513/0001-60': 1,
  '00.000.000/0001-91': 1,
  '10.507.466/0001-31': 1,
  '07.553.129/0001-76': 1,
  '17.731.703/0001-92': 1,
  '09.605.345/0001-43': 1,
  '08.060.934/0001-20': 1,
  '04.064.641/0001-60': 1,
  '10.445.253/0001-22': 1,
  '10.319.076/0001-38': 1,
  '10.831.701/0001-26': 1,
  '40.787.152/0001-09': 1,
  '63.478.895/0001-94': 1,
  '07.917.492/0001-23': 1,
  '09.245.424/0001-90': 1,
  '04.051.269/0001-58': 1,
  '17.415.972/0001-40': 1,
  '10.555.446/0001-36': 1,
  '568.444.844-53': 1,
  '15.085.199/0001-75': 1,
  '24.298.895/0001-50': 1,
  '12.397.179/0001-41': 1,
  '14.866.736/0001-51': 1,
  '337.884.538-42': 1,
  '288.097.568-94': 1,
  '10.523.901/0001-11': 1,
  '12.910.493/0001-86': 1,
  '08.757.585/0001-09': 1,
  '30.822.936/0001-69': 1,
  '03.708.204/0001-70': 1,
  '090.263.134-97': 1,
  '10.482.492/0001-52': 1,
  '721.723.043-87': 1,
  '092.043.174-77': 1,
  '06.224.321/0001-56': 1,
  '17.372.598/0001-42': 1,
  '023.724.913-85': 1,
  '067.930.534-34': 1,
  '009.069.874-66': 1,
  '41.150.368/0001-13': 1,
  '40.982.464/0001-65': 1,
  '09.297.961/0001-84': 1,
  '15.717.891/0001-79': 1,
  '674.739.894-72': 1,
  '03.723.339/0002-95': 1,
  '24.502.049/0001-00': 1,
  '046.825.704-71': 1,
  '752.939.354-53': 1,
  '065.769.294-80': 1,
  '082.365.704-36': 1,
  '098.513.724-04': 1,
  '219.732.104-87': 1,
  '069.161.174-27': 1,
  '054.047.524-67': 1,
  '00.210.590/0001-87': 1,
  '40.977.555/0001-02': 1,
  '077.781.584-26': 1,
  '09.087.693/0001-76': 1,
  '14.140.752/0001-62': 1,
  '15.783.593/0001-87': 1,
  '024.761.594-33': 1,
  '034.169.144-57': 1,
  '346.613.103-06': 1,
  '01.982.830/0001-24': 1,
  '486.925.494-87': 1,
  '00.394.460/0058-87': 1,
  '10.346.175/0001-09': 1,
  '10.806.118/0001-65': 1,
  '07.936.090/0001-76': 1,
  '064.226.544-56': 1,
  '08.948.054/0001-95': 1,
  '027.787.354-10': 1,
  '072.226.678-22': 1,
  '030.480.134-82': 1,
  '10.963.942/0001-29': 1,
  '024.618.834-08': 1,
  '037.002.274-26': 1,
  '048.510.934-46': 1,
  '032.132.678-48': 1,
  '043.694.814-14': 1,
  '805.249.584-91': 1,
  '086.059.324-06': 1,
  '067.744.604-70': 1,
  '798.363.214-20': 1,
  '051.688.974-52': 1,
  '044.447.298-30': 1,
  '078.096.424-13': 1,
  '051.175.584-80': 1,
  '264.348.668-44': 1,
  '395.780.464-72': 1,
  '131.556.168-90': 1,
  '041.219.194-67': 1,
  '17.318.988/0001-34': 1,
  '09.632.818/0001-00': 1,
  '096.353.614-16': 1,
  '10.761.617/0001-83': 1,
  '05.321.071/0001-00': 1,
  '032.500.774-88': 1,
  '12.931.457/0001-07': 1,
  '295.190.998-59': 1,
  '102.068.674-09': 1,
  '093.729.086-65': 1,
  '011.331.514-77': 1,
  '14.968.974/0001-78': 1,
  '808.451.503-91': 1,
  '752.935.794-87': 1,
  '056.770.754-77': 1,
  '146.743.388-83': 1,
  '12.305.387/0001-73': 1,
  '05.505.947/0001-78': 1,
  '019.911.524-93': 1,
  '050.070.774-02': 1,
  '065.158.224-56': 1,
  '131.995.488-06': 1,
  '04.601.397/0001-28': 1,
  '548.842.173-49': 1,
  '603.131.884-91': 1,
  '024.072.554-96': 1,
  '361.934.101-04': 1,
  '042.763.584-50': 1,
  '202.471.878-79': 1,
  '323.782.758-46': 1,
  '024.026.814-89': 1,
  '086.766.624-28': 1,
  '392.239.574-00': 1,
  '03.328.487/0003-96': 1,
  '010.996.155-26': 1,
  '252.051.294-68': 1,
  '14.745.112/0001-86': 1,
  '08.778.268/0001-60': 1,
  '97.542.560/0001-00': 1,
  '739.303.344-53': 1,
  '141.967.274-68': 1,
  '045.306.703-41': 1,
  '032.612.684-84': 1,
  '15.345.033/0001-40': 1,
  '048.426.314-57': 1,
  '918.390.764-53': 1,
  '102.480.758-45': 1,
  '060.538.274-36': 1,
  '13.121.240/0001-96': 1,
  '12.825.186/0002-88': 1,
  '112.272.554-03': 1,
  '079.765.324-48': 1,
  '872.882.494-68': 1,
  '486.277.804-63': 1,
  '10.918.256/0001-36': 1,
  '17.184.648/0001-68': 1,
  '08.170.634/0001-02': 1,
  '01.023.823/0001-03': 1,
  '131.657.848-84': 1,
  '115.361.914-85': 1,
  '062.051.284-97': 1,
  '563.348.691-91': 1,
  '35.503.721/0001-07': 1,
  '18.110.206/0001-30': 1,
  '108.588.614-02': 1,
  '04.420.916/0008-28': 1,
  '17.695.673/0001-06': 1,
  '760.800.054-68': 1,
  '01.843.743/0001-96': 1,
  '068.907.374-74': 1,
  '030.757.694-95': 1,
  '009.112.684-30': 1,
  '063.663.374-89': 1,
  '600.962.414-20': 1,
  '09.101.082/0001-35': 1,
  '091.179.764-56': 1,
  '104.130.744-63': 1,
  '181.171.204-53': 1,
  '35.583.343/0001-00': 1,
  '01.722.296/0001-17': 1,
  '125.850.738-23': 1,
  '06.328.947/0001-02': 1,
  '018.154.044-42': 1,
  '083.100.104-60': 1,
  '020.975.004-98': 1,
  '427.841.664-49': 1,
  '570.173.604-00': 1,
  '014.433.354-60': 1,
  '520.460.285-20': 1,
  '054.851.163-29': 1,
  '109.825.194-60': 1,
  '805.998.004-10': 1,
  '049.208.404-11': 1,
  '03.846.266/0001-48': 1,
  '923.879.421-91': 1,
  '674.578.864-00': 1,
  '967.641.803-00': 1,
  '500.453.934-00': 1,
  '083.705.114-22': 1,
  '057.166.464-41': 1,
  '568.453.914-91': 1,
  '009.191.783-24': 1,
  '09.478.023/0001-80': 1,
  '09.127.069/0001-55': 1,
  '123.379.434-53': 1,
  '443.528.321-20': 1,
  '036.709.584-01': 1,
  '74.686.262/0001-98': 1,
  '298.405.384-20': 1,
  '020.863.984-50': 1,
  '094.516.384-31': 1,
  '063.561.384-08': 1,
  '010.466.564-57': 1,
  '100.989.404-81': 1,
  '090.127.654-55': 1,
  '009.564.884-47': 1,
  '610.316.581-49': 1,
  '00.983.013/0001-28': 1,
  '319.518.993-34': 1,
  '302.575.574-15': 1,
  '14.101.322/0001-31': 1,
  '08.791.659/0001-15': 1,
  '238.212.994-87': 1,
  '055.325.395-61': 1,
  '07.115.086/0001-47': 1,
  '01.524.627/0001-04': 1,
  '008.164.894-40': 1,
  '01.704.290/0001-17': 1,
  '02.477.571/0001-47': 1,
  '07.597.013/0001-39': 1,
  '007.808.084-36': 1,
  '395.128.354-87': 1,
  '009.982.284-94': 1,
  '029.972.344-50': 1,
  '065.647.854-37': 1,
  '160.896.504-04': 1,
  '674.579.084-04': 1,
  '034.695.014-75': 1,
  '090.966.014-08': 1,
  '44.287.712/0001-09': 1,
  '035.949.658-05': 1,
  '070.584.874-48': 1,
  '017.215.764-10': 1,
  '08.766.032/0002-95': 1,
  '050.439.654-44': 1,
  '15.131.435/0001-42': 1,
  '14.206.061/0001-14': 1,
  '059.349.783-06': 1,
  '964.744.754-04': 1,
  '40.982.464/0002-46': 1,
  '010.941.684-83': 1,
  '020.667.704-93': 1,
  '439.641.174-04': 1,
  '450.985.144-87': 1,
  '098.675.458-77': 1,
  '066.519.744-67': 1,
  '17.047.535/0001-10': 1,
  '351.674.591-68': 1,
  '09.600.404/0001-90': 1,
  '035.408.363-57': 1,
  '11.426.166/0001-90': 1,
  '20.443.238/0001-07': 1,
  '024.753.524-93': 1,
  '058.381.364-05': 1,
  '061.370.064-33': 1,
  '18.138.067/0001-52': 1,
  '071.399.844-09': 1,
  '071.880.874-66': 1,
  '029.795.084-38': 1,
  '023.515.834-85': 1,
  '06.203.898/0001-81': 1,
  '090.290.374-82': 1,
  '690.369.344-00': 1,
  '02.750.635/0001-31': 1,
  '087.580.634-12': 1,
  '02.349.756/0001-76': 1,
  '17.979.880/0001-92': 1,
  '48.015.119/0001-64': 1,
  '06.985.921/0001-37': 1,
  '020.077.404-27': 1,
  '017.652.104-61': 1,
  '09.492.800/0001-41': 1,
  '12.842.064/0001-19': 1,
  '10.308.192/0001-51': 1,
  '063.613.524-12': 1,
  '034.047.244-88': 1,
  '00.463.305/0001-30': 1,
  '05.465.986/0001-99': 1,
  '05.457.283/0002-08': 1,
  '12.613.238/0001-71': 1,
  '931.314.024-15': 1,
  '35.501.295/0001-64': 1,
  '15.407.975/0001-06': 1,
  '037.540.184-93': 1,
  '046.768.394-80': 1,
  '840.807.104-10': 1,
  '036.968.024-33': 1,
  '027.000.074-76': 1,
  '01.245.055/0001-24': 1,
  '15.510.104/0001-13': 1,
  '03.160.232/0001-03': 1,
  '19.252.387/0001-00': 1,
  '035.580.284-81': 1,
  '41.097.684/0001-79': 1,
  '277.273.208-89': 1,
  '148.027.674-04': 1,
  '10.144.577/0001-20': 1,
  '093.259.824-20': 1,
  '586.697.289-15': 1,
  '738.558.394-68': 1,
  '08.561.990/0001-49': 1,
  '061.704.354-02': 1,
  '691.948.408-06': 1,
  '068.346.874-08': 1,
  '04.953.021/0001-82': 1,
  '024.613.524-70': 1,
  '02.168.943/0001-53': 1,
  '09.402.419/0001-44': 1,
  '105.292.714-94': 1,
  '06.824.439/0002-04': 1,
  '10.718.163/0001-68': 1,
  '096.658.344-28': 1,
  '046.658.074-69': 1,
  '662.979.901-15': 1,
  '981.213.834-04': 1,
  '05.286.407/0001-40': 1,
  '065.876.084-00': 1,
  '160.969.578-03': 1,
  '451.013.294-87': 1,
  '057.148.164-71': 1,
  '35.210.897/0001-62': 1,
  '13.167.781/0001-55': 1,
  '004.406.204-49': 1,
  '09.146.028/0001-06': 1,
  '41.124.546/0001-31': 1,
  '00.394.544/0127-87': 1,
  '06.370.630/0001-34': 1,
  '20.219.206/0001-14': 1,
  '17.293.645/0001-62': 1,
  '057.247.874-74': 1,
  '022.044.964-30': 1,
  '05.590.101/0001-83': 1,
  '083.025.774-80': 1,
  '101.657.674-99': 1,
  '071.873.784-91': 1,
  '21.547.317/0001-12': 1,
  '040.901.224-65': 1,
  '16.837.482/0001-79': 1,
  '044.369.014-67': 1,
  '17.337.665/0001-98': 1,
  '21.784.773/0001-86': 1,
  '029.644.714-52': 1,
  '175.193.798-41': 1,
  '054.813.044-22': 1,
  '342.627.684-49': 1,
  '414.317.744-72': 1,
  '010.328.064-27': 1,
  '086.384.844-37': 1,
  '526.399.244-00': 1,
  '09.386.533/0001-28': 1,
  '21.227.963/0001-00': 1,
  '16.826.043/0001-60': 1,
  '09.283.185/0001-63': 1,
  '115.599.804-94': 1,
  '019.997.784-48': 1,
  '898.333.254-91': 1,
  '01.024.347/0001-37': 1,
  '16.513.357/0001-03': 1,
  '003.058.930-41': 1,
  '10.554.743/0001-67': 1,
  '007.643.924-09': 1,
  '024.167.114-07': 1,
  '068.224.024-97': 1,
  '03.789.726/0001-43': 1,
  '027.168.664-22': 1,
  '108.568.824-02': 1,
  '04.342.393/0001-72': 1,
  '17.758.807/0001-90': 1,
  '185.953.671-91': 1,
  '079.833.784-24': 1,
  '036.541.284-83': 1,
  '151.265.364-00': 1,
  '20.794.299/0001-00': 1,
  '038.674.304-54': 1,
  '35.572.494/0001-63': 1,
  '893.447.314-20': 1,
  '037.835.994-07': 1,
  '54.177.761/0001-42': 1,
  '031.748.894-56': 1,
  '027.237.604-30': 1,
  '10.592.570/0001-71': 1,
  '893.468.314-72': 1,
  '037.006.554-95': 1,
  '16.526.536/0001-85': 1,
  '17.852.505/0001-87': 1,
  '049.162.344-56': 1,
  '873.991.214-00': 1,
  '172.374.868-45': 1,
  '360.048.044-87': 1,
  '073.236.304-79': 1,
  '34.028.316/3663-53': 1,
  '050.027.184-42': 1,
  '079.803.284-77': 1,
  '066.994.358-41': 1,
  '05.675.713/0001-79': 1,
  '024.751.324-50': 1,
  '078.418.774-63': 1,
  '437.046.704-72': 1,
  '16.466.494/0001-34': 1,
  '035.376.544-99': 1,
  '059.745.534-11': 1,
  '089.570.994-50': 1,
  '087.801.634-16': 1,
  '113.773.044-77': 1,
  '056.386.254-88': 1,
  '059.577.934-42': 1,
  '486.260.234-72': 1,
  '676.409.154-49': 1,
  '101.373.634-60': 1,
  '031.910.564-40': 1,
  '343.082.704-30': 1,
  '219.955.674-34': 1,
  '112.478.944-87': 1,
  '077.028.604-64': 1,
  '092.053.414-79': 1,
  '035.194.184-36': 1,
  '089.515.334-33': 1,
  '056.212.894-80': 1,
  '051.795.634-96': 1,
  '066.088.124-18': 1,
  '060.834.054-59': 1,
  '029.322.264-95': 1,
  '094.599.004-96': 1,
  '075.167.224-64': 1,
  '080.365.034-50': 1,
  '060.452.244-42': 1,
  '073.946.054-42': 1,
  '020.006.104-63': 1,
  '036.944.904-50': 1,
  '036.993.134-33': 1,
  '036.988.144-39': 1,
  '918.315.394-20': 1,
  '065.711.484-71': 1,
  '043.745.584-03': 1,
  '082.733.584-96': 1,
  '10.748.147/0001-18': 1,
  '07.314.245/0001-32': 1,
  '981.302.424-00': 1,
  '101.132.324-97': 1,
  '010.287.094-20': 1,
  '12.695.319/0001-68': 1,
  '338.257.854-91': 1,
  '010.505.354-64': 1,
  '085.693.794-04': 1,
  '042.602.394-30': 1,
  '839.414.284-20': 1,
  '031.895.674-84': 1,
  '066.355.454-33': 1,
  '14.921.086/0001-08': 1,
  '044.037.904-02': 1,
  '03.965.517/0001-03': 1,
  '058.457.424-04': 1,
  '09.610.221/0001-56': 1,
  '050.188.814-45': 1,
  '031.913.524-14': 1,
  '095.036.774-59': 1,
  '34.028.316/0019-32': 1,
  '03.270.191/0001-08': 1,
  '24.280.828/0001-09': 1,
  '025.877.314-61': 1,
  '145.313.328-30': 1,
  '02.940.722/0001-51': 1,
  '052.425.994-13': 1,
  '026.940.403-14': 1,
  '10.976.739/0001-97': 1,
  '028.099.554-76': 1,
  '10.818.853/0001-99': 1,
  '016.156.094-66': 1,
  '075.510.174-02': 1,
  '18.995.457/0001-49': 1,
  '16.779.292/0001-42': 1,
  '096.612.924-50': 1,
  '027.800.314-17': 1,
  '07.797.967/0001-95': 1,
  '049.192.044-00': 1,
  '361.566.044-72': 1,
  '056.456.484-20': 1,
  '250.520.268-03': 1,
  '055.924.914-41': 1,
  '031.897.194-11': 1,
  '041.640.098-10': 1,
  '884.839.244-04': 1,
  '350.577.004-30': 1,
  '992.702.854-72': 1,
  '037.558.954-63': 1,
  '759.579.304-15': 1,
  '578.106.483-49': 1,
  '14.313.179/0001-41': 1,
  '225.537.624-53': 1,
  '046.078.684-93': 1,
  '02.375.199/0001-68': 1,
  '298.407.754-72': 1,
  '046.450.334-50': 1,
  '013.811.474-96': 1,
  '518.396.954-04': 1,
  '038.307.964-04': 1,
  '000.911.984-10': 1,
  '087.899.544-75': 1,
  '805.258.574-00': 1,
  '037.746.684-00': 1,
  '08.744.768/0001-81': 1,
  '403.466.253-00': 1,
  '037.168.314-92': 1,
  '214.329.748-31': 1,
  '713.838.084-49': 1,
  '01.208.840/0001-07': 1,
  '100.499.024-31': 1,
  '059.533.604-36': 1,
  '918.654.684-87': 1,
  '130.330.184-91': 1,
  '078.814.524-04': 1,
  '032.514.044-82': 1,
  '048.698.044-84': 1,
  '412.677.614-15': 1,
  '045.640.014-18': 1,
  '103.468.194-07': 1,
  '23.982.276/0001-18': 1,
  '01.146.404/0001-50': 1,
  '188.644.494-34': 1,
  '052.204.984-28': 1,
  '095.318.444-70': 1,
  '114.435.858-23': 1,
  '646.564.974-87': 1,
  '22.769.247/0001-00': 1,
  '249.107.913-53': 1,
  '02.977.362/0001-62': 1,
  '022.380.774-56': 1,
  '022.223.724-45': 1,
  '983.034.904-78': 1,
  '064.507.524-83': 1,
  '502.467.984-91': 1,
  '090.263.114-43': 1,
  '014.306.154-27': 1,
  '059.483.614-03': 1,
  '354.549.958-86': 1,
  '805.255.474-87': 1,
  '101.553.054-09': 1,
  '065.934.364-96': 1,
  '101.579.554-43': 1,
  '710.235.494-09': 1,
  '066.081.274-64': 1,
  '044.748.004-94': 1,
  '038.891.944-27': 1,
  '16.978.480/0001-08': 1,
  '23.476.946/0001-24': 1,
  '09.402.406/0001-75': 1,
  '760.809.004-91': 1,
  '068.515.874-83': 1,
  '117.112.254-36': 1,
  '032.711.954-39': 1,
  '068.362.734-14': 1,
  '008.980.684-01': 1,
  '014.996.914-75': 1,
  '12.023.197/0001-63': 1,
  '02.714.801/0001-44': 1,
  '14.402.326/0001-50': 1,
  '19.173.082/0001-02': 1,
  '028.963.764-37': 1,
  '057.707.364-88': 1,
  '070.044.424-62': 1,
  '029.312.724-77': 1,
  '10.464.359/0001-73': 1,
  '933.991.034-68': 1,
  '064.919.814-01': 1,
  '018.361.303-17': 1,
  '030.188.844-26': 1,
  '859.243.693-15': 1,
  '025.396.464-41': 1,
  '051.134.353-17': 1,
  '225.415.194-00': 1,
  '12.085.495/0001-88': 1,
  '071.477.494-48': 1,
  '992.636.024-68': 1,
  '29.979.036/0169-00': 1,
  '055.127.244-95': 1,
  '012.393.604-79': 1,
  '218.821.694-68': 1,
  '053.603.864-36': 1,
  '866.317.997-91': 1,
  '018.499.224-97': 1,
  '297.266.958-48': 1,
  '121.257.284-00': 1,
  '063.316.834-37': 1,
  '076.660.674-02': 1,
  '11.054.242/0001-84': 1,
  '11.064.297/0001-75': 1,
  '02.075.682/0001-27': 1,
  '600.923.784-04': 1,
  '027.236.074-02': 1,
  '027.794.504-60': 1,
  '004.949.773-10': 1,
  '098.536.624-93': 1,
  '121.226.924-13': 1,
  '038.413.134-42': 1,
  '080.659.394-65': 1,
  '108.826.414-09': 1,
  '15.218.561/0001-39': 1,
  '169.897.728-08': 1,
  '08.321.484/0001-82': 1,
  '03.843.541/0001-70': 1,
  '20.870.418/0001-67': 1,
  '24.257.785/0001-40': 1,
  '08.282.077/0001-03': 1,
  '22.501.077/0001-88': 1,
  '05.888.881/0001-42': 1,
  '16.715.147/0001-06': 1,
  '110.614.854-12': 1,
  '030.578.924-42': 1,
  '102.852.974-06': 1,
  '031.906.634-75': 1,
  '041.558.554-61': 1,
  '101.638.884-50': 1,
  '022.386.864-79': 1,
  '009.157.304-13': 1,
  '088.729.724-26': 1,
  '983.141.654-68': 1,
  '09.611.740/0001-39': 1,
  '093.313.234-41': 1,
  '203.682.404-87': 1,
  '658.257.561-91': 1,
  '091.548.134-09': 1,
  '026.044.354-97': 1,
  '113.036.664-21': 1,
  '039.504.364-64': 1,
  '20.174.368/0001-83': 1,
  '874.016.494-20': 1,
  '19.012.469/0001-79': 1,
  '069.608.314-07': 1,
  '101.130.684-09': 1,
  '090.944.464-13': 1,
  '19.088.423/0001-33': 1,
  '23.540.416/0001-06': 1,
  '21.262.327/0001-01': 1,
  '043.279.974-55': 1,
  '437.050.814-20': 1,
  '067.811.084-09': 1,
  '100.011.524-08': 1,
  '100.394.108-70': 1,
  '601.389.634-87': 1,
  '101.131.494-09': 1,
  '147.827.664-91': 1,
  '08.829.277/0001-33': 1,
  '037.009.854-44': 1,
  '759.989.554-04': 1,
  '194.470.928-29': 1,
  '058.649.794-30': 1,
  '274.610.924-72': 1,
  '992.480.694-87': 1,
  '088.576.764-04': 1,
  '044.388.313-00': 1,
  '073.104.094-50': 1,
  '030.193.434-70': 1,
  '013.743.254-22': 1,
  '41.207.317/0001-80': 1,
  '321.324.334-53': 1,
  '049.076.424-07': 1,
  '042.458.834-05': 1,
  '037.887.234-67': 1,
  '22.404.799/0001-14': 1,
  '033.078.964-31': 1,
  '578.111.564-15': 1,
  '05.193.717/0001-10': 1,
  '046.850.934-88': 1,
  '674.753.884-68': 1,
  '100.665.144-60': 1,
  '098.341.564-13': 1,
  '061.697.844-82': 1,
  '079.858.414-90': 1,
  '069.132.814-55': 1,
  '281.941.918-66': 1,
  '701.966.884-42': 1,
  '603.495.144-53': 1,
  '019.773.784-63': 1,
  '000.815.704-90': 1,
  '535.869.054-91': 1,
  '095.039.614-16': 1,
  '391.386.233-15': 1,
  '096.964.544-90': 1,
  '067.551.884-92': 1,
  '061.764.834-41': 1,
  '028.949.924-08': 1,
  '059.574.454-01': 1,

In [29]:
df_dados_completos_tratados_2020['CONCAT_CODIGO'] = df_dados_completos_tratados_2020.apply(lambda x: x['CPF/CNPJ'] + '-' + str(x['TIPO']), axis=1)
df_dados_completos_tratados_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO,CONCAT_CODIGO
0,1722010101,cotaparte do icms,03/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,185560.68,1,08.923.971/0001-15-1
1,1722010101,cotaparte do icms,04/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,8081.80,1,08.923.971/0001-15-1
2,1722010101,cotaparte do icms,07/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,4231.39,1,08.923.971/0001-15-1
3,1722010101,cotaparte do icms,08/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,10536.53,1,08.923.971/0001-15-1
4,1722010101,cotaparte do icms,15/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,103118.27,1,08.923.971/0001-15-1

In [30]:
df_contribuintes_receitas_2020 = pd.DataFrame(df_dados_completos_tratados_2020[['CPF/CNPJ','CONTRIBUINTE','TIPO','CONCAT_CODIGO']])
df_contribuintes_receitas_2020.drop_duplicates(subset='CONCAT_CODIGO', inplace=True)
df_contribuintes_receitas_2020.reset_index(drop=True)
df_contribuintes_receitas_2020[['TIPO']].value_counts()

TIPO
1       1181
2         20
3          4
dtype: int64

In [31]:
df_dados_completos_tratados_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO,CPF/CNPJ
0,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,6224.78,1,sem informacao
1,132100111,remuneracao de depositos bancarios principal,01/12/2021,banco do brasil sa,-6224.78,1,sem informacao
2,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,722577.64,1,sem informacao
3,171809111,transferencias de recursos da complementacao ...,01/12/2021,banco do brasil sa,-722577.64,1,sem informacao
4,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,1166975.68,1,sem informacao

In [32]:
dic_valores_2022 = df_to_dict(df_dados_completos_2022,'CONTRIBUINTE','TIPO','TIPO')
dic_valores_2022

{1: {'banco do brasil sa': 1,
  'sec educeducinfantil ii  fundeb  efetivos': 1,
  'sec educeduc infantil i  fundeb  efetivos': 1,
  'camara municipal de cajazeiras': 1,
  'prefeitura municipal de cajazeiras': 1,
  'caixa economica federal': 1,
  'kelly dayse ferreira da silva': 1,
  'maxicon  construcoes e servicos ltda': 1,
  'cbr empreendimentos imobiliarios limitada': 1,
  'sec de saude  samu  contratados': 1,
  'sec de saude  caps  contratados': 1,
  'sec de saude contratados  mac  covid19': 1,
  'sec saude  prog sad melhor em casa  contrat': 1,
  'sec de saude  ceo  contratados': 1,
  'sec de saude contratados  psf': 1,
  'sec de saude  policlinica  contratados': 1,
  'sec de saude  sede contratados': 1,
  'gomes  santos servicos de radioprotecao ltda  me': 1,
  'emanuelle tuanny fiuza avelino': 1,
  'neurocentro centro de neu e met de diag ltda': 1,
  'maria aparecida pereira rodrigues': 1,
  'jose heber moreno cavalcante': 1,
  'sec educadminfantil  mde  efetivos': 1,
  'sec edu merendeiras  mde  efetivos': 1,
  'sec educadm fundament mde  efetivos': 1,
  'sec comunicacao  efetivos': 1,
  'sec meio ambinte  efetivos': 1,
  '47 sec  desenvolvimento economico e empreendedorismo  efetivos': 1,
  '163  sec da juventude esporte e lazer  efetivos': 1,
  'bruno jose de freitas': 1,
  'jucelio costa de araujo e cia ltda': 1,
  'jose de sousa sa juniorcaja ferro': 1,
  'f dalberto eireli': 1,
  'anderline telecomunicacoes e multimidia ltda': 1,
  'cedrul centro de diagnostico por imagem ltda': 1,
  'j v comercio de derivados de petroleo ltda': 1,
  'manoel alcindo de andrade': 1,
  'construpav construtora ltda': 1,
  'alves e freitas ltda  me': 1,
  'melo supermercado ltda': 1,
  'sec educensfundamental ii  fundeb  efetivos': 1,
  'sec educensfundamental i  fundeb  efetivos': 1,
  'sec de saude  samu  comissionados': 1,
  'sec de saude  policlinica  comissionados': 1,
  'sec de saude  psf  comissionados': 1,
  'sec de saudecontratados': 1,
  'central do construtor comercio varejista de material de construcao ltdame': 1,
  'jocileide do nascimento campos': 1,
  'sec educ biblioteca   mde  efetivos': 1,
  'c mendes feitosa': 1,
  'maria iriana coura u pordeus': 1,
  'sec mun desenv humano  contbolsa familia': 1,
  'francisco luciano de oliveira  xerox': 1,
  'suzaneide gomes cavalcanti': 1,
  'g  c assessoria e consultoria eireli': 1,
  'mcr pneus ltda': 1,
  'francisco edilson vieira  epp': 1,
  'pedro mangueira de aquino': 1,
  'pag pouco celularrusbenio lira bezerra': 1,
  'biomeddisthospe labonosssenha conc': 1,
  'ferreira e brito locacoes de automoveis maquinas': 1,
  'elianise viana oliveiracristalina pocos': 1,
  'goncala ferreira pontes eireli': 1,
  'sec de saude  comissionados': 1,
  'jose rennan de souza satiro': 1,
  'inforprinter comercio  servicos limitada  me': 1,
  'robenilson firmino da silva': 1,
  'nogueira coleta de residuos ltda': 1,
  'sec mun desenv humanoprogramas  efetivos': 1,
  'sec mun desenv humano  efetivos': 1,
  'farmacia coracao de jesus ltda  me': 1,
  'sec de saudepoliclinica  efetivos': 1,
  'sec de saudeacspacs  efetivos': 1,
  'superintendencia cajazeirense de transito sctran': 1,
  'eliane do nascimento campos': 1,
  'sec de saudepsf  efetivos': 1,
  'mauro celso formiga gomes 02376193427': 1,
  'sec mun desenv humano  contcras ii': 1,
  'sec de saude  samu  efetivos': 1,
  'secmunhumano  prog crianca feliz  cont': 1,
  'secmundesenv  creas i  contratados': 1,
  'sec mun desenv humano  scfortvinc  cont': 1,
  'secmun desenv humano  contcras i': 1,
  'thais de oliveira brandao  me': 1,
  'secmundesenv humanosprog  comissionados': 1,
  'sao paulo consig ltda': 1,
  'm t goncalves  me': 1,
  'sec de saude  efetivos': 1,
  'sec de saude  peva  efetivos': 1,
  'leonardo varandas sociedade individual de advocaci': 1,
  'lenilson souza dos santos 03095902484': 1,
  'claudineia leitao martins satiro me': 1,
  'elmarprocessamento de dados ltda': 1,
  'eticons  empresa de tecnologia de informacao e consultoria ltda': 1,
  'rodrigo maia advocacia': 1,
  'c renato m da silva': 1,
  'alexandra pereira de lima 06519014486': 1,
  'energisa paraiba dist de enegia sa': 1,
  'sec comunicacao  comissionados': 1,
  'sec desenvolvimento economico e empreendedorismo  comissionados': 1,
  'sec meio ambiente  comissionados': 1,
  'sec munpolitpub para as mulheres  comiss': 1,
  'sec mun cultura e turismo  comissionados': 1,
  'sec juventude esporte e lazer  comissionados': 1,
  'sec municipal do controle social  comissionados': 1,
  'sec governo e art politica  comissionados': 1,
  'procuradoria geral do municipio  comissionados': 1,
  'sec des rural e rec hidricos  comissionados': 1,
  'sec infraestrutura  comissionados': 1,
  'sec fazenda publica  comissionados': 1,
  'sec administracao  comissionados': 1,
  'sec planejamento  comissionados': 1,
  '41sec mun polit pub para as mulheres  efetivos': 1,
  'seg governo e art politica  efetivos': 1,
  'sec administracao  efetivos': 1,
  'sec infraestrutura  efetivos': 1,
  'sec fazenda publica  efetivos': 1,
  'sec governo e art politica  eletivo': 1,
  'm l dantas construcoes eireli': 1,
  '232seceducensfundamental ii  contrato  mde': 1,
  '231seceducensfundamental i  contrato  mde': 1,
  'sala 10 comunicacao ltda': 1,
  'freitas servicos de engenharia ltda': 1,
  'colinas construcoes transportes e servicos eireli': 1,
  'sec educ  comissionado  mde': 1,
  'procuradoria geral do municipio  efetivos': 1,
  'sec municipal do controle social  efetivos': 1,
  'sec planejamento  efetivos': 1,
  'sec de saude caps ad iii  efetivos': 1,
  'sec de saude  nasf  efetivos': 1,
  'sec de saude  farmacia basica  efetivos': 1,
  'sec de saude  centro de reab audit  efetivos': 1,
  'sec de saude caps infantil  efetivos': 1,
  'sec de saude caps ad  efetivos': 1,
  'sec de saudeceo  efetivos': 1,
  'sec de saude caps 2  efetivos': 1,
  'thomas jeferson lima de aquino': 1,
  'instituto de previdencia e assistencia municipal': 1,
  'lacil lab de analises clinicas dr isaac lordao ltda  me': 1,
  'classic viagens e turismo ltda  epp': 1,
  'paulo sostenes moreira rangel': 1,
  'guerbet produtos radiologicos limitada': 1,
  'valterlins lacerda dos santos 98132113420': 1,
  'umberto ferreira dos santos  me': 1,
  'valderi alves ferreira filho': 1,
  'george emerson leite carolino': 1,
  'frutuoso alves de andrade': 1,
  'evolution digital': 1,
  'cristina de sousa claudino': 1,
  'francisco juvencio de araujo': 1,
  'abik engenharia e consultoria ltda': 1,
  'sec de saude  nasf  contratados': 1,
  'raimundo rodrigues': 1,
  'dalton pedrosa rocha': 1,
  'rayne almeida de brito lima me': 1,
  'ceara diesel sa': 1,
  'marcondes oliveira de souza': 1,
  'clair  leitao contabilidade publica ltda  me': 1,
  'sec de saude  residencia terapeutica  efetivos': 1,
  'adriano dos santos jales': 1,
  'cicero monteiro da silva': 1,
  'francisca de lourdes da silva rodrigues': 1,
  'clinica gastroenterologica prontogastro ltda ss  me': 1,
  'dimedont  dist de med e equip ltda': 1,
  'vicente goncalves de oliveira': 1,
  'gilberlan de souza alves': 1,
  'mikael douglas ferreira da silva 07827837409': 1,
  'leia com de livros e magazine ltda': 1,
  'itarget tecnologia da informacao ltda': 1,
  'gadelha e victor ltda': 1,
  'waste coleta de residuos hospitalares': 1,
  'hospital de olhos de cajazeiras ltda': 1,
  'ednaldo goncalves da silva': 1,
  'nnmeddistribuicao importacao e exportacao de med': 1,
  'luzia de aquino ferreiraamerican pneus': 1,
  'secmun desenv humano  cca contratados': 1,
  'ecologica construcoes e servicos eirelime': 1,
  'fundo nacional de desenvolvimento da educacao': 1,
  'adl linkprovedor de internet via radio': 1,
  'sec des rural e rec hidricos  efetivos': 1,
  'sme servicos especializados ltda': 1,
  'galvao magazine ltda': 1,
  'acm auto center maquinas eireli': 1,
  '4health servicos medicos ltda': 1,
  'george emanuel alves da silva': 1,
  'imperio do papel comercio de papeis ltda': 1,
  'danielle skarlett de lima araujo': 1,
  'industria editora  grafica real ltda': 1,
  'a casa construcoes e servicos ltda  me': 1,
  'matias oliveira silva': 1,
  'americo cavalcante chianaca neto  me': 1,
  '368sec politicas publicas  comissionados': 1,
  'sec de saude  caps  comissionados': 1,
  'budega da musica comercio e servicos eireli me': 1,
  'a p a brandao junior eireli': 1,
  'lc  construcoes locacoes e servicos eireli': 1,
  'cwc distribuidora ltda': 1,
  'emilly industria e comercio de moveis ltda': 1,
  'joao paulo de sousa braz': 1,
  'locar empreendimentos eireli': 1,
  'lucimar marques galvao': 1,
  'maxicasa comercio construcoes e servicos ltda  m': 1,
  'km expresso transporte de cargas eireli': 1,
  'maria perpetua paz 08833649806': 1,
  'maria do socorro adelino moura': 1,
  'joabson farias vieira': 1,
  'aws solucoes servicos e construcoes ltda': 1,
  'paulo de araujo eireli': 1,
  'jose waltemar rolim  w matias rolim  mobilart': 1,
  'francisco lucas estrela de almeida': 1,
  'lacerda e brasil comercio de pecas automotivas ltdame': 1,
  'vital e soares ltda me  me': 1,
  'neuziene garcia pereira': 1,
  'sec politicas publicas  efetivos': 1,
  'oi movel sa  em recuperacao judicial': 1,
  'telemar norte leste saoi fixo': 1,
  'acacia construcoes ltda  epp': 1,
  'edineide lira de souza sa': 1,
  'jose laercio alves praeixo': 1,
  'fundo municipal de saude de cajazeiras': 1,
  'fundo municipal de saude de cajazeirinhas': 1,
  'ministerio do desenvolvimento regional': 1,
  'melo e martins comercio varejista de alimentos ltda': 1,
  '42sec educeduc infantil i  fundeb  efetivos': 1,
  '36sec edu merendeiras  mde  efetivos': 1,
  'valzimar gomes de souza': 1,
  'gilderlane ferreira da silva': 1,
  'lider servicos locacoes e empreendimentos eireli': 1,
  'valcivan soares de carvalho': 1,
  '316sec governo e art politica  eletivo': 1,
  'departamento de estradas de rodagem do estado da pb': 1,
  '29sec educ  comissionado  mde': 1,
  '317sec governo e art politica  comissionados': 1,
  '353sec municipal do controle social  comissionados': 1,
  '369sec juventude esporte e lazer  comissionados': 1,
  '372sec munpolitpub para as mulheres  comiss': 1,
  '202sec educcontratados  mde': 1,
  '374sec desenvolvimento economico e empreendedorismo  comissionados': 1,
  '373sec meio ambiente  comissionados': 1,
  '371sec mun cultura e turismo  comissionados': 1,
  '314procuradoria geral do municipio  comissionados': 1,
  '311sec des rural e rec hidricos  comissionados': 1,
  '310sec infraestrutura  comissionados': 1,
  '304sec administracao  comissionados': 1,
  '308sec fazenda publica  comissionados': 1,
  '301sec planejamento  comissionados': 1,
  '375sec comunicacao  comissionados': 1,
  'gomes e costa ltda': 1,
  'lacerda  goldfarb ltda': 1,
  '07sec infraestrutura  efetivos': 1,
  '06sec fazenda publica  efetivos': 1,
  '01seg governo e art politica  efetivos': 1,
  '04sec administracao  efetivos': 1,
  '43sec educensfundamental i  fundeb  efetivos': 1,
  '44sec educensfundamental ii  fundeb  efetivos': 1,
  '35sec educ biblioteca   mde  efetivos': 1,
  '34sec educadm fundament mde  efetivos': 1,
  '33sec educadminfantil  mde  efetivos': 1,
  'rg magagine ltda  me': 1,
  '26sec municipal do controle social  efetivos': 1,
  '48sec comunicacao  efetivos': 1,
  '47  sec  desenvolvimento economico e empreendedorismo  efetivos': 1,
  '46sec meio ambiente  efetivos': 1,
  '17 sec da juventude esporte e lazer  efetivos': 1,
  '12procuradoria geral do municipio  efetivos': 1,
  '02sec planejamento  efetivos': 1,
  'cledson lima almeida me': 1,
  '13deg 33  sec educadminfantil  mde  efetivos': 1,
  '13o 34  sec educadm fundament mde  efetivos': 1,
  '13deg 36sec educ merendeiras  mde  efetivos': 1,
  '13o 42  sec educadminfantil  mde  efetivos': 1,
  '13deg 43  sec educensfundamental i  fundeb  efetivos': 1,
  '13deg 44sec educensfundamental ii  fundeb  efetivos': 1,
  '13o 01seg governo e art politica  efetivos': 1,
  '13deg 26  controladoria geral do municipio  efetivos': 1,
  '13o 35sec educ biblioteca   mde  efetivos': 1,
  '13deg 41sec mun polit pub para as mulheres  efetivos': 1,
  '13deg 48sec comunicacao  efetivos': 1,
  '13deg 46  sec meio ambiente  efetivos': 1,
  '13deg 17   sec da juventude esporte e lazer  efetivos': 1,
  '13o 12procuradoria geral do municipio  efetivos': 1,
  '13o 07sec infraestrutura  efetivos': 1,
  '13o 06sec fazenda publica  efetivos': 1,
  '13o 04sec administracao  efetivos': 1,
  '13o 02sec planejamento  efetivos': 1,
  '13deg 374sec desenvolvimento economico e empreendedorismo  comissionados': 1,
  '13deg 373sec meio ambiente  comissionados': 1,
  '13deg 372sec munpolitpub para as mulheres  comiss': 1,
  '13deg 371sec mun cultura e turismo  comissionados': 1,
  '13deg 369  sec juventude e lazer  comissionados': 1,
  '13deg 311  sec des rural e rec hidricos  comissionados': 1,
  '13deg 310  sec infraestrutura  comissionados': 1,
  '13deg 29  sec educ  comissionado': 1,
  '13deg 301  sec planejamento  comissionados': 1,
  '13deg 304  sec administracao  comissionados': 1,
  '13deg 308sec fazenda publica  comissionados': 1,
  '13deg 314  procuradoria geral do municipio  comissionados': 1,
  '13deg 317  sec governo e art politica  comissionados': 1,
  '13deg 353  controladoria geral do municipio  comissionados': 1,
  '13deg 375sec comunicacao  comissionados': 1,
  'joao francisco de sousa filho': 1,
  'camila vilar moesia': 1,
  'construtora 2 irmaos ltda': 1,
  'milor perfuracoes e engenharia eireli': 1,
  'marcos augusto duarte coelho filho 10416744494': 1,
  'geo referencia topografia projetos e construcoes limitada': 1,
  'r  m construcoes e reformas ltda': 1,
  'maria romanilly furtado massena': 1,
  'vera mainny lima pereira': 1,
  'jose wilton dantas da silva': 1,
  'victor emanuel paulino de menezes': 1,
  'joelson goncalves da silva nunes': 1,
  'tacianne priscyla mathias': 1,
  'wanderley ferreira de oliveira': 1,
  'wendel pires de almeida': 1,
  'vanessa lourenco da silva': 1,
  '10sec des rural e rec hidricos  efetivos': 1,
  'credense servicos eireli': 1,
  'bruna yohane figueiredo rolim andrade': 1,
  'cassiano maia neto': 1,
  'canapu comercio de distribuicao ltda  me': 1,
  'francinelio candido amaro': 1,
  'francisco de assis franca da silva': 1,
  'antonio aduilio rodrigues mendes me': 1,
  '305  sec da administracao  contratados': 1,
  'departamento nacional de obras contra as secas': 1,
  'joelma maria goncalves rolim da silva': 1,
  'com de racoes e prod agrop alcindo ltda': 1,
  'h moreno comercio de maquinas e implementos agricolas ltda': 1,
  'n j freitas comercio de material': 1,
  'phelipe henrique alves sousa': 1,
  'melo bagaceira e contrucoes eireli': 1,
  'jocileide do nascimento campos 02253576409': 1,
  'francisco tiberio de alencar moreira eireli': 1,
  'inssinst nacional do seguro social': 1,
  'paraiba  placas e servicos graficos  michelle soares  08065956475': 1,
  'sec mun desenv humano  conselho tutelar': 1,
  'sidclay de moura bezerra': 1,
  'narjara rolim dos santos 05853881485': 1,
  'g pinheiro ltda': 1,
  'selma maria lisboa alves de queiroz 44122993415': 1,
  'jose sandro teodosio da silva': 1,
  'divina comercio de moveis e equipamentos para escritorio ltda': 1,
  'grafica realclaudio gomes f e cia ltda': 1,
  'islane santos da silva': 1,
  'safetec informatica ltda': 1,
  'maria das gracas marques de oliveira 04226022483': 1,
  'antonio helano vieira da silva segundo': 1},
 2: {'prefeitura municipal de cajazeiras': 2,
  'caixa economica federal': 2,
  'banco do brasil sa': 2,
  '2  inativos': 2,
  'fundo municipal de saude de cajazeiras': 2,
  'superintendencia cajazeirense de transito': 2,
  'fundo de assistencia social de cajazeiras': 2,
  'camara municipal de cajazeiras': 2,
  'maria aparecida pereira rodrigues': 2,
  'inss': 2,
  '29 pensionistas': 2},
 3: {'banco do brasil sa': 3,
  'r2 mobbi sistemas e mobilidade urbana eireli': 3}}

In [33]:
df_dados_completos_tratados_2022['CONCAT_CODIGO'] = df_dados_completos_tratados_2022.apply(lambda x: x['CONTRIBUINTE'] + '-' + str(x['TIPO']), axis=1)
df_dados_completos_tratados_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO,CPF/CNPJ,CONCAT_CODIGO
0,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,6224.78,1,sem informacao,banco do brasil sa-1
1,132100111,remuneracao de depositos bancarios principal,01/12/2021,banco do brasil sa,-6224.78,1,sem informacao,banco do brasil sa-1
2,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,722577.64,1,sem informacao,banco do brasil sa-1
3,171809111,transferencias de recursos da complementacao ...,01/12/2021,banco do brasil sa,-722577.64,1,sem informacao,banco do brasil sa-1
4,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,1166975.68,1,sem informacao,banco do brasil sa-1

In [34]:
df_contribuintes_receitas_2022 = pd.DataFrame(df_dados_completos_tratados_2022[['CPF/CNPJ','CONTRIBUINTE','TIPO','CONCAT_CODIGO']])
df_contribuintes_receitas_2022.drop_duplicates(subset='CONCAT_CODIGO', inplace=True)
df_contribuintes_receitas_2022.reset_index(drop=True)
df_contribuintes_receitas_2022[['TIPO']].value_counts()

TIPO
1       348
2        11
3         2
dtype: int64

## Merge dos Df

### Merge dos dados dos contribuintes

In [35]:
df_contribuinte_merged = merge_dataframes(df_contribuintes_receitas_2020, df_contribuintes_receitas_2022)
df_contribuinte_merged

,CPF/CNPJ,CONTRIBUINTE,TIPO,CONCAT_CODIGO
0,08.923.971/0001-15,prefeitura municipal de cajazeiras,1,08.923.971/0001-15-1
1,00.360.305/0040-10,caixa economica federal,1,00.360.305/0040-10-1
2,sem informacao,fopag,1,sem informacao-1
3,603.496.544-68,juramir oliveira de sousa,1,603.496.544-68-1
4,064.659.174-67,paula lais de oliveira santana,1,064.659.174-67-1
...,...,...,...,...
1561,sem informacao,safetec informatica ltda,1,safetec informatica ltda-1
1562,042.260.224-83,maria das gracas marques de oliveira,1,maria das gracas marques de oliveira -1
1563,sem informacao,antonio helano vieira da silva segundo,1,antonio helano vieira da silva segundo-1
1564,29.979.036/0169-00,inss,2,inss-2
1565,sem informacao,29 pensionistas,2,29 pensionistas-2

In [36]:
df_contribuinte_merged[['TIPO']].value_counts()

TIPO
1       1529
2         31
3          6
dtype: int64

In [37]:
df_contribuinte_merged = gerar_codigo_unico(df_contribuinte_merged,'CONCAT_CODIGO')
df_contribuinte_merged.sort_values(['TIPO'], ascending=True, inplace=True)
df_contribuinte_merged.reset_index(drop=True)

,CPF/CNPJ,CONTRIBUINTE,TIPO,CONCAT_CODIGO,CODIGO
0,08.923.971/0001-15,prefeitura municipal de cajazeiras,1,08.923.971/0001-15-1,886cd0eabf5a18
1,038.628.134-36,joao jose de andrade sobrinho,1,038.628.134-36-1,af7e52bc3ee1a8
2,911.164.224-68,clara maria honorato,1,911.164.224-68-1,09dace633966e6
3,070.405.144-35,fopag creas i,1,070.405.144-35-1,2ec12bef7667c1
4,00.448.994/0001-03,classic viagens e turismo eireli me,1,00.448.994/0001-03-1,eefb6011a40df6
...,...,...,...,...,...
1561,sem informacao,r2 mobbi sistemas e mobilidade urbana eireli,3,r2 mobbi sistemas e mobilidade urbana eireli-3,83b6cedab10e79
1562,00.000.000/0099-03,banco do brasil sa,3,banco do brasil sa-3,e6da541375c18b
1563,04.342.393/0001-72,superintendencia cajazeirense de transito,3,04.342.393/0001-72-3,470c93ab945237
1564,00.360.305/0040-10,caixa economica federal,3,00.360.305/0040-10-3,7995e22912c93c
1565,00.000.000/0099-03,banco do brasil sa,3,00.000.000/0099-03-3,23c9e86250ba86

In [38]:
def remove_espacos_duplos(df):
    # copia o DataFrame original
    df_copy = df.copy()
    # itera sobre as colunas do DataFrame
    for col in df_copy.columns:
        # verifica se a coluna é do tipo 'object' (string)
        if df_copy[col].dtype == 'O':
            # remove espaços duplicados da coluna
            df_copy[col] = df_copy[col].str.replace('\s+', ' ')
    return df_copy

In [39]:
df_contribuinte_merged = remove_espacos_duplos(df_contribuinte_merged)

C:\Users\allys\AppData\Local\Temp\ipykernel_18296\2630336717.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df_copy[col] = df_copy[col].str.replace('\s+', ' ')

In [40]:
dic_fonte_dados = {1:'prefeitura municipal',
                   2:'instituto de previdencia e assistencia social',
                   3:'sctrans',
                   4:'camara municipal'}

In [41]:
df_contribuinte_merged.head()

,CPF/CNPJ,CONTRIBUINTE,TIPO,CONCAT_CODIGO,CODIGO
0,08.923.971/0001-15,prefeitura municipal de cajazeiras,1,08.923.971/0001-15-1,886cd0eabf5a18
1040,038.628.134-36,joao jose de andrade sobrinho,1,038.628.134-36-1,af7e52bc3ee1a8
1039,911.164.224-68,clara maria honorato,1,911.164.224-68-1,09dace633966e6
1038,070.405.144-35,fopag creas i,1,070.405.144-35-1,2ec12bef7667c1
1037,00.448.994/0001-03,classic viagens e turismo eireli me,1,00.448.994/0001-03-1,eefb6011a40df6

In [42]:
df_contribuinte_merged_atualizado = df_contribuinte_merged.copy()
df_contribuinte_merged_atualizado['TIPO'] = df_contribuinte_merged_atualizado['TIPO'].replace(dic_fonte_dados)
df_contribuinte_merged_atualizado.value_counts()

CPF/CNPJ            CONTRIBUINTE                                            TIPO                  CONCAT_CODIGO              CODIGO
00.000.000/0001-91  banco do brasil sa                                      prefeitura municipal  00.000.000/0001-91-1       67e077177e7903    1
24.103.251/0001-60  elegantecamisetas e fardamentos                         prefeitura municipal  24.103.251/0001-60-1       fc8e7d6540112b    1
26.918.460/0001-97  g m de alencar fernandes                                prefeitura municipal  26.918.460/0001-97-1       b8ce8e0caa4011    1
26.903.980/0001-26  mamute producoes e servicos ltda                        prefeitura municipal  26.903.980/0001-26-1       bafec577fd376d    1
26.695.440/0001-02  consultoria florestal ambiental e engenharia eireli me  prefeitura municipal  26.695.440/0001-02-1       185a80a42b36c9    1
                                                                                                                                              ..
077.769.074-80      maria tamires damascena de souza                        prefeitura municipal  077.769.074-80-1           ddc6b23a27a6c8    1
077.411.244-12      germano bismar apolinario                               prefeitura municipal  077.411.244-12-1           c72c6336b50faa    1
077.028.604-64      eduardo jose pereira                                    prefeitura municipal  077.028.604-64-1           17e7d407c90876    1
076.660.674-02      antonio vieira rolim filho                              prefeitura municipal  076.660.674-02-1           cf08e4d9bd9778    1
sem informacao      wendel pires de almeida                                 prefeitura municipal  wendel pires de almeida-1  d0bc12dfbd7fb6    1
Length: 1566, dtype: int64

In [43]:
save_dataframe(df_contribuinte_merged_atualizado,'dados_contribuintes_receita')

with open('arquivos_para_carga/dados_contribuintes_receita.csv', 'w', encoding='utf-8', newline='') as f:
    df_contribuinte_merged_atualizado.to_csv(f, **csv_kwargs)

## Dados Receita

In [44]:
df_contribuinte = merge_dataframes(df_contribuintes_receitas_2020, df_contribuintes_receitas_2022)
df_contribuinte = gerar_codigo_unico(df_contribuinte,'CONCAT_CODIGO')
df_contribuinte.sort_values(['TIPO'], ascending=True, inplace=True)
df_contribuinte_codigo = pd.DataFrame(df_contribuinte[['CONCAT_CODIGO', 'CODIGO']])
df_contribuinte_codigo.reset_index(drop=True)

                                       CONCAT_CODIGO          CODIGO
0                               08.923.971/0001-15-1  886cd0eabf5a18
1                                   038.628.134-36-1  af7e52bc3ee1a8
2                                   911.164.224-68-1  09dace633966e6
3                                   070.405.144-35-1  2ec12bef7667c1
4                               00.448.994/0001-03-1  eefb6011a40df6
...                                              ...             ...
1561  r2 mobbi sistemas e mobilidade urbana eireli-3  83b6cedab10e79
1562                            banco do brasil sa-3  e6da541375c18b
1563                            04.342.393/0001-72-3  470c93ab945237
1564                            00.360.305/0040-10-3  7995e22912c93c
1565                            00.000.000/0099-03-3  23c9e86250ba86

[1566 rows x 2 columns]

In [45]:
df_dados_completos_tratados_2020.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,CPF/CNPJ,VALOR PREVISTO,VALOR ARRECADADO,TIPO,CONCAT_CODIGO
0,1722010101,cotaparte do icms,03/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,185560.68,1,08.923.971/0001-15-1
1,1722010101,cotaparte do icms,04/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,8081.80,1,08.923.971/0001-15-1
2,1722010101,cotaparte do icms,07/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,4231.39,1,08.923.971/0001-15-1
3,1722010101,cotaparte do icms,08/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,10536.53,1,08.923.971/0001-15-1
4,1722010101,cotaparte do icms,15/01/2013,prefeitura municipal de cajazeiras,08.923.971/0001-15,8362000.0,103118.27,1,08.923.971/0001-15-1

In [46]:
df_dados_2020=pd.merge(df_dados_completos_tratados_2020, df_contribuinte_codigo, on='CONCAT_CODIGO', how='left')
df_dados_completos_2020 = pd.DataFrame(df_dados_2020[['CODIGO_x','DATA','VALOR ARRECADADO','TIPO','CODIGO_y']])
df_dados_completos_2020.rename({'CODIGO_x':'COD_RECEITA','TIPO':'FONTE_DADOS','CODIGO_y':'COD_CONTRIBUINTE','VALOR ARRECADADO':'VALOR_ARRECADADO'}, axis=1, inplace=True)
df_dados_completos_2020 = df_dados_completos_2020.reindex(['COD_RECEITA','DATA','COD_CONTRIBUINTE','VALOR_ARRECADADO','FONTE_DADOS'], axis=1)
df_dados_completos_2020['DATA'] = pd.to_datetime(df_dados_completos_2020['DATA'], format='%d/%m/%Y')

df_dados_completos_2020

       COD_RECEITA       DATA COD_CONTRIBUINTE  VALOR_ARRECADADO  FONTE_DADOS
0       1722010101 2013-01-03   886cd0eabf5a18         185560.68            1
1       1722010101 2013-01-04   886cd0eabf5a18           8081.80            1
2       1722010101 2013-01-07   886cd0eabf5a18           4231.39            1
3       1722010101 2013-01-08   886cd0eabf5a18          10536.53            1
4       1722010101 2013-01-15   886cd0eabf5a18         103118.27            1
...            ...        ...              ...               ...          ...
85559   1910011100 2020-12-29   23c9e86250ba86            482.76            3
85560   1990991100 2020-12-30   23c9e86250ba86           2189.44            3
85561   1910011100 2020-12-30   23c9e86250ba86            274.35            3
85562   1321001103 2020-12-31   23c9e86250ba86              1.54            3
85563   1121011102 2020-12-31   23c9e86250ba86           1409.60            3

[85564 rows x 5 columns]

In [47]:
df_dados_completos_tratados_2022.head()

,CODIGO,RECEITA,DATA,CONTRIBUINTE,VALOR ARRECADADO,TIPO,CPF/CNPJ,CONCAT_CODIGO
0,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,6224.78,1,sem informacao,banco do brasil sa-1
1,132100111,remuneracao de depositos bancarios principal,01/12/2021,banco do brasil sa,-6224.78,1,sem informacao,banco do brasil sa-1
2,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,722577.64,1,sem informacao,banco do brasil sa-1
3,171809111,transferencias de recursos da complementacao ...,01/12/2021,banco do brasil sa,-722577.64,1,sem informacao,banco do brasil sa-1
4,175801111,transferencias de recursos do fundo de manute...,01/12/2021,banco do brasil sa,1166975.68,1,sem informacao,banco do brasil sa-1

In [48]:
df_dados_2022=pd.merge(df_dados_completos_tratados_2022, df_contribuinte_codigo, on='CONCAT_CODIGO', how='left')
df_dados_completos_2022 = pd.DataFrame(df_dados_2022[['CODIGO_x','DATA','VALOR ARRECADADO','TIPO','CODIGO_y']])
df_dados_completos_2022.rename({'CODIGO_x':'COD_RECEITA','TIPO':'FONTE_DADOS','CODIGO_y':'COD_CONTRIBUINTE','VALOR ARRECADADO':'VALOR_ARRECADADO'}, axis=1, inplace=True)
df_dados_completos_2022 = df_dados_completos_2022.reindex(['COD_RECEITA','DATA','COD_CONTRIBUINTE','VALOR_ARRECADADO','FONTE_DADOS'], axis=1)
df_dados_completos_2022['DATA'] = pd.to_datetime(df_dados_completos_2022['DATA'], format='%d/%m/%Y')

df_dados_completos_2022

       COD_RECEITA       DATA COD_CONTRIBUINTE  VALOR_ARRECADADO  FONTE_DADOS
0        175801111 2021-12-01   5c3f0f5bd2471d           6224.78            1
1        132100111 2021-12-01   5c3f0f5bd2471d          -6224.78            1
2        175801111 2021-12-01   5c3f0f5bd2471d         722577.64            1
3        171809111 2021-12-01   5c3f0f5bd2471d        -722577.64            1
4        175801111 2021-12-01   5c3f0f5bd2471d        1166975.68            1
...            ...        ...              ...               ...          ...
16724    191101011 2022-01-19   e6da541375c18b           4374.24            3
16725    112101011 2022-01-18   e6da541375c18b            228.00            3
16726    191101011 2022-01-18   e6da541375c18b           3758.69            3
16727    112101011 2022-01-17   e6da541375c18b           4297.00            3
16728    191101011 2022-01-17   e6da541375c18b          78032.06            3

[16729 rows x 5 columns]

In [49]:
df_receitas = pd.concat([df_dados_completos_2020, df_dados_completos_2022])
df_receitas

       COD_RECEITA       DATA COD_CONTRIBUINTE  VALOR_ARRECADADO  FONTE_DADOS
0       1722010101 2013-01-03   886cd0eabf5a18         185560.68            1
1       1722010101 2013-01-04   886cd0eabf5a18           8081.80            1
2       1722010101 2013-01-07   886cd0eabf5a18           4231.39            1
3       1722010101 2013-01-08   886cd0eabf5a18          10536.53            1
4       1722010101 2013-01-15   886cd0eabf5a18         103118.27            1
...            ...        ...              ...               ...          ...
16724    191101011 2022-01-19   e6da541375c18b           4374.24            3
16725    112101011 2022-01-18   e6da541375c18b            228.00            3
16726    191101011 2022-01-18   e6da541375c18b           3758.69            3
16727    112101011 2022-01-17   e6da541375c18b           4297.00            3
16728    191101011 2022-01-17   e6da541375c18b          78032.06            3

[102293 rows x 5 columns]

In [50]:
df_receitas = remove_espacos_duplos(df_receitas)
df_receitas.head()

C:\Users\allys\AppData\Local\Temp\ipykernel_18296\2630336717.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df_copy[col] = df_copy[col].str.replace('\s+', ' ')

   COD_RECEITA       DATA COD_CONTRIBUINTE  VALOR_ARRECADADO  FONTE_DADOS
0   1722010101 2013-01-03   886cd0eabf5a18         185560.68            1
1   1722010101 2013-01-04   886cd0eabf5a18           8081.80            1
2   1722010101 2013-01-07   886cd0eabf5a18           4231.39            1
3   1722010101 2013-01-08   886cd0eabf5a18          10536.53            1
4   1722010101 2013-01-15   886cd0eabf5a18         103118.27            1

In [51]:
df_receitas_atualizado = df_receitas.copy()
df_receitas_atualizado['FONTE_DADOS'] = df_receitas_atualizado['FONTE_DADOS'].replace(dic_fonte_dados)
df_receitas_atualizado['FONTE_DADOS'].value_counts()

prefeitura municipal                             94025
sctrans                                           4706
instituto de previdencia e assistencia social     3562
Name: FONTE_DADOS, dtype: int64

In [52]:
save_dataframe(df_receitas_atualizado,'dados_receitas')

with open('arquivos_para_carga/dados_receitas.csv', 'w', encoding='utf-8', newline='') as f:
    df_receitas_atualizado.to_csv(f, **csv_kwargs)